// lib/data.js — All lesson content and module structure

export const MODULES = [
  {
    id: 'A1', icon: '🌱', color: 'a1', locked: false,
    label: { en: 'A1 — Beginner', pa: 'A1 — ਸ਼ੁਰੂਆਤੀ', es: 'A1 — Principiante', hi: 'A1 — शुरुआती', ar: 'A1 — مبتدئ' },
    desc:  { en: 'Greetings, numbers, colors, family — zero to first conversations', pa: 'ਸ਼ੁਭਕਾਮਨਾਵਾਂ, ਨੰਬਰ, ਰੰਗ, ਪਰਿਵਾਰ', es: 'Saludos, números, colores, familia', hi: 'अभिवादन, संख्याएँ, रंग, परिवार', ar: 'تحيات وأرقام وألوان وعائلة' },
    lessons: ['a1-1', 'a1-2', 'a1-3', 'a1-4'],
  },
  {
    id: 'A2', icon: '📗', color: 'a2', locked: false,
    label: { en: 'A2 — Elementary', pa: 'A2 — ਮੁੱਢਲਾ', es: 'A2 — Elemental', hi: 'A2 — प्रारंभिक', ar: 'A2 — ابتدائي' },
    desc:  { en: 'Present tense verbs, daily routines, time, descriptions', pa: 'ਵਰਤਮਾਨ ਕਾਲ, ਰੋਜ਼ਾਨਾ ਜ਼ਿੰਦਗੀ, ਸਮਾਂ', es: 'Presente, rutina, hora, descripciones', hi: 'वर्तमान काल, दैनिक दिनचर्या, समय', ar: 'المضارع والروتين والوقت' },
    lessons: ['a2-1', 'a2-2'],
  },
  {
    id: 'B1', icon: '📘', color: 'b1', locked: true,
    label: { en: 'B1 — Intermediate', pa: 'B1 — ਵਿਚਕਾਰਲਾ', es: 'B1 — Intermedio', hi: 'B1 — मध्यवर्ती', ar: 'B1 — متوسط' },
    desc:  { en: 'Past tense, opinions, work & professional contexts', pa: 'ਭੂਤ ਕਾਲ, ਵਿਚਾਰ, ਕਿੱਤਾ', es: 'Pasado, opiniones, trabajo', hi: 'भूत काल, राय, कार्यस्थल', ar: 'الماضي والآراء والعمل' },
    lessons: [],
  },
  {
    id: 'B2', icon: '📙', color: 'b2', locked: true,
    label: { en: 'B2 — Upper Intermediate', pa: 'B2 — ਉੱਚ ਵਿਚਕਾਰਲਾ', es: 'B2 — Intermedio alto', hi: 'B2 — उच्च मध्यवर्ती', ar: 'B2 — متوسط متقدم' },
    desc:  { en: 'Complex grammar, nuanced speech, advanced vocabulary', pa: 'ਗੁੰਝਲਦਾਰ ਵਿਆਕਰਨ, ਉੱਚ ਸ਼ਬਦਾਵਲੀ', es: 'Gramática compleja, vocabulario avanzado', hi: 'जटिल व्याकरण, उन्नत शब्दावली', ar: 'قواعد معقدة ومفردات متقدمة' },
    lessons: [],
  },
  {
    id: 'TEF', icon: '🏆', color: 'tef', locked: true,
    label: { en: 'TEF Prep — CLB 7+', pa: 'TEF ਤਿਆਰੀ — CLB 7+', es: 'Preparación TEF — CLB 7+', hi: 'TEF तैयारी — CLB 7+', ar: 'التحضير لـ TEF — CLB 7+' },
    desc:  { en: 'Exam simulation: reading, writing, listening, speaking', pa: 'ਇਮਤਿਹਾਨ ਸਿਮੂਲੇਸ਼ਨ', es: 'Simulación del examen TEF', hi: 'परीक्षा सिमुलेशन', ar: 'محاكاة امتحان TEF' },
    lessons: [],
  },
];

export const LESSONS = {

  // ─── A1 ───────────────────────────────────────────────────────────────────

  'a1-1': {
    id: 'a1-1', moduleId: 'A1', icon: '👋', xp: 25,
    title: { en: 'Greetings & Basics', pa: 'ਸ਼ੁਰੂਆਤੀ ਸ਼ਬਦ', es: 'Saludos básicos', hi: 'बुनियादी अभिवादन', ar: 'التحيات الأساسية' },
    concept: {
      en: `In French, greetings change by time of day and formality. "Bonjour" is the universal daytime greeting. After around 6pm, switch to "Bonsoir." The casual "Salut" is only for friends — never use it with strangers, employers, or officials. The formal "vous" vs informal "tu" distinction is critical in all of Canadian French.`,
      pa: `ਫ੍ਰੈਂਚ ਵਿੱਚ, ਸ਼ੁਭਕਾਮਨਾਵਾਂ ਦਿਨ ਦੇ ਸਮੇਂ ਅਤੇ ਰਸਮੀਅਤ ਅਨੁਸਾਰ ਬਦਲਦੀਆਂ ਹਨ। "Bonjour" ਦਿਨ ਵੇਲੇ ਦੀ ਸਰਵਵਿਆਪਕ ਸ਼ੁਭਕਾਮਨਾ ਹੈ। "Bonsoir" ਸ਼ਾਮ ਦੀ ਸ਼ੁਭਕਾਮਨਾ ਹੈ। "Vous" ਰਸਮੀ ਹੈ, "tu" ਗੈਰ-ਰਸਮੀ — ਇਹ ਫ਼ਰਕ ਬਹੁਤ ਜ਼ਰੂਰੀ ਹੈ।`,
      es: `En francés, los saludos cambian según la hora y la formalidad. "Bonjour" se usa durante el día. Después de las 6pm, usa "Bonsoir." "Salut" es solo para amigos. La distinción entre "vous" (formal) y "tu" (informal) es fundamental en el francés canadiense.`,
      hi: `फ्रेंच में, अभिवादन समय और औपचारिकता के अनुसार बदलते हैं। "Bonjour" दिन का सार्वभौमिक अभिवादन है। शाम 6 बजे के बाद "Bonsoir" का उपयोग करें। "Salut" केवल दोस्तों के लिए है। "vous" (औपचारिक) बनाम "tu" (अनौपचारिक) का अंतर बहुत महत्वपूर्ण है।`,
      ar: `في الفرنسية، تتغير التحيات حسب وقت اليوم ودرجة الرسمية. "Bonjour" هي التحية النهارية الشاملة. بعد الساعة السادسة مساءً، استخدم "Bonsoir". "Salut" للأصدقاء فقط. التمييز بين "vous" الرسمية و"tu" غير الرسمية أساسي في الفرنسية الكندية.`,
    },
    vocab: [
      { fr: 'Bonjour',              ph: 'bohn-ZHOOR',          en: 'Hello / Good morning',         pa: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ / ਸ਼ੁਭ ਸਵੇਰ',     es: 'Hola / Buenos días',     hi: 'नमस्ते / सुप्रभात',       ar: 'مرحبا / صباح الخير' },
      { fr: 'Bonsoir',              ph: 'bohn-SWAHR',          en: 'Good evening',                 pa: 'ਸ਼ੁਭ ਸੰਧਿਆ',                  es: 'Buenas tardes/noches',   hi: 'शुभ संध्या',              ar: 'مساء الخير' },
      { fr: 'Salut',                ph: 'sah-LUE',             en: 'Hi — informal only',           pa: 'ਹੈਲੋ (ਸਿਰਫ਼ ਗੈਰ-ਰਸਮੀ)',         es: 'Hola (informal)',        hi: 'हाय (केवल अनौपचारिक)',   ar: 'أهلاً (غير رسمي فقط)' },
      { fr: 'Au revoir',            ph: 'oh ruh-VWAHR',        en: 'Goodbye',                      pa: 'ਅਲਵਿਦਾ',                      es: 'Adiós',                  hi: 'अलविदा',                  ar: 'وداعاً' },
      { fr: 'Merci',                ph: 'mer-SEE',             en: 'Thank you',                    pa: 'ਧੰਨਵਾਦ',                      es: 'Gracias',                hi: 'धन्यवाद',                 ar: 'شكراً' },
      { fr: "S'il vous plaît",      ph: 'seel voo PLAY',       en: 'Please (formal)',              pa: 'ਕਿਰਪਾ ਕਰਕੇ (ਰਸਮੀ)',            es: 'Por favor (formal)',     hi: 'कृपया (औपचारिक)',        ar: 'من فضلك (رسمي)' },
      { fr: 'Oui / Non',            ph: 'WEE / NOH',           en: 'Yes / No',                     pa: 'ਹਾਂ / ਨਹੀਂ',                  es: 'Sí / No',                hi: 'हाँ / नहीं',              ar: 'نعم / لا' },
      { fr: "Je m'appelle…",        ph: "zhuh mah-PELL",       en: 'My name is…',                  pa: 'ਮੇਰਾ ਨਾਮ ਹੈ…',                es: 'Me llamo…',              hi: 'मेरा नाम है…',            ar: 'اسمي…' },
      { fr: 'Comment allez-vous?',  ph: 'koh-MAHN ta-lay-VOO', en: 'How are you? (formal)',        pa: 'ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ? (ਰਸਮੀ)',       es: '¿Cómo está usted?',     hi: 'आप कैसे हैं? (औपचारिक)', ar: 'كيف حالك؟ (رسمي)' },
      { fr: 'Très bien, merci',     ph: 'treh BYEH mer-SEE',   en: 'Very well, thank you',         pa: 'ਬਹੁਤ ਵਧੀਆ, ਧੰਨਵਾਦ',            es: 'Muy bien, gracias',      hi: 'बहुत अच्छा, धन्यवाद',   ar: 'بخير جداً، شكراً' },
    ],
    exercises: [
      { q: { en: "How do you say 'Hello' in French?", pa: "ਫ੍ਰੈਂਚ ਵਿੱਚ 'ਹੈਲੋ' ਕਿਵੇਂ?", es: "¿'Hola' en francés?", hi: "'Hello' फ्रेंच में?", ar: "كيف تقول 'مرحبا'؟" },
        opts: ['Bonjour','Merci','Au revoir','Salut'], ans: 0 },
      { q: { en: "What does 'Merci' mean?", pa: "'Merci' ਦਾ ਮਤਲਬ?", es: "¿Qué significa 'Merci'?", hi: "'Merci' का अर्थ?", ar: "ما معنى 'Merci'؟" },
        opts: ['Please','Goodbye','Thank you','Yes'], ans: 2 },
      { q: { en: "Which greeting is informal?", pa: "ਕਿਹੜੀ ਸ਼ੁਭਕਾਮਨਾ ਗੈਰ-ਰਸਮੀ ਹੈ?", es: "¿Cuál es informal?", hi: "कौन सा अनौपचारिक है?", ar: "أي تحية غير رسمية؟" },
        opts: ['Bonjour','Bonsoir','Salut','Au revoir'], ans: 2 },
      { q: { en: "'Au revoir' means:", pa: "'Au revoir' ਦਾ ਮਤਲਬ:", es: "'Au revoir' significa:", hi: "'Au revoir' का अर्थ:", ar: "'Au revoir' تعني:" },
        opts: ['Hello','Thank you','Please','Goodbye'], ans: 3 },
      { q: { en: "'Je m'appelle' means:", pa: "'Je m'appelle' ਦਾ ਮਤਲਬ:", es: "'Je m'appelle' significa:", hi: "'Je m'appelle' का अर्थ:", ar: "'Je m'appelle' تعني:" },
        opts: ['I go','I have','My name is','I am'], ans: 2 },
    ],
  },

  'a1-2': {
    id: 'a1-2', moduleId: 'A1', icon: '🔢', xp: 25,
    title: { en: 'Numbers 1–20', pa: 'ਨੰਬਰ 1–20', es: 'Números 1–20', hi: 'संख्याएँ 1–20', ar: 'الأرقام 1-20' },
    concept: {
      en: `French numbers from 1–16 are unique words you must memorize. From 17–19, they follow a compound pattern: dix-sept (ten-seven), dix-huit (ten-eight), dix-neuf (ten-nine). 20 is "vingt." Numbers are essential for addresses, phone numbers, prices, and your age — all things you'll need daily in Canada.`,
      pa: `ਫ੍ਰੈਂਚ ਨੰਬਰ 1–16 ਵਿਲੱਖਣ ਸ਼ਬਦ ਹਨ। 17–19 ਮਿਸ਼ਰਿਤ ਨਮੂਨੇ: dix-sept (10+7), dix-huit (10+8), dix-neuf (10+9)। 20 = vingt. ਕੈਨੇਡਾ ਵਿੱਚ ਰੋਜ਼ਾਨਾ ਵਰਤੋਂ ਲਈ ਜ਼ਰੂਰੀ।`,
      es: `Los números 1–16 son palabras únicas. 17–19 siguen el patrón compuesto: dix-sept, dix-huit, dix-neuf. 20 es "vingt." Esenciales para precios, direcciones y la vida diaria en Canadá.`,
      hi: `फ्रेंच संख्याएं 1–16 अद्वितीय शब्द हैं। 17–19 यौगिक पैटर्न: dix-sept (10+7), dix-huit (10+8), dix-neuf (10+9)। 20 = vingt. कनाडा में दैनिक जीवन के लिए आवश्यक।`,
      ar: `الأرقام 1–16 كلمات فريدة. 17–19 تتبع نمطاً مركباً: dix-sept (10+7)، dix-huit (10+8)، dix-neuf (10+9). 20 = vingt. ضرورية للحياة اليومية في كندا.`,
    },
    vocab: [
      { fr: 'un / deux / trois',   ph: 'UHN / DUH / TWAH',      en: '1 / 2 / 3',  pa: '1 / 2 / 3', es: '1 / 2 / 3', hi: '1 / 2 / 3', ar: '1 / 2 / 3' },
      { fr: 'quatre / cinq / six', ph: 'KAH-truh / SANK / SEES', en: '4 / 5 / 6',  pa: '4 / 5 / 6', es: '4 / 5 / 6', hi: '4 / 5 / 6', ar: '4 / 5 / 6' },
      { fr: 'sept / huit / neuf',  ph: 'SET / WEET / NUF',       en: '7 / 8 / 9',  pa: '7 / 8 / 9', es: '7 / 8 / 9', hi: '7 / 8 / 9', ar: '7 / 8 / 9' },
      { fr: 'dix / onze / douze',  ph: 'DEES / OHNZ / DOOZ',     en: '10 / 11 / 12', pa: '10/11/12', es: '10/11/12', hi: '10/11/12', ar: '10/11/12' },
      { fr: 'treize / quatorze',   ph: 'TREHZ / kah-TORZ',       en: '13 / 14',    pa: '13 / 14', es: '13 / 14', hi: '13 / 14', ar: '13 / 14' },
      { fr: 'quinze / seize',      ph: 'KANZ / SEZ',             en: '15 / 16',    pa: '15 / 16', es: '15 / 16', hi: '15 / 16', ar: '15 / 16' },
      { fr: 'dix-sept / dix-huit', ph: 'dee-SET / dee-WEET',     en: '17 / 18 (ten+7, ten+8)', pa: '17/18', es: '17/18', hi: '17/18', ar: '17/18' },
      { fr: 'dix-neuf / vingt',    ph: 'dee-NUF / VAN',          en: '19 / 20',    pa: '19 / 20', es: '19 / 20', hi: '19 / 20', ar: '19 / 20' },
      { fr: "J'ai vingt ans",      ph: "zhay VAN ahn",           en: 'I am 20 years old', pa: 'ਮੈਂ 20 ਸਾਲ ਦਾ ਹਾਂ', es: 'Tengo 20 años', hi: 'मैं 20 साल का हूँ', ar: 'عمري 20 سنة' },
    ],
    exercises: [
      { q: { en: "How do you say '5'?", pa: "'5' ਫ੍ਰੈਂਚ ਵਿੱਚ?", es: "¿'5' en francés?", hi: "'5' फ्रेंच में?", ar: "كيف تقول '5'؟" },
        opts: ['quatre','cinq','six','sept'], ans: 1 },
      { q: { en: "'Douze' equals:", pa: "'Douze' ਬਰਾਬਰ:", es: "'Douze' equivale a:", hi: "'Douze' बराबर:", ar: "'Douze' يساوي:" },
        opts: ['10','11','12','13'], ans: 2 },
      { q: { en: "17 in French is:", pa: "ਫ੍ਰੈਂਚ ਵਿੱਚ 17:", es: "17 en francés:", hi: "फ्रेंच में 17:", ar: "17 بالفرنسية:" },
        opts: ['seize','dix-sept','dix-huit','dix-neuf'], ans: 1 },
      { q: { en: "'Vingt' means:", pa: "'Vingt' ਦਾ ਮਤਲਬ:", es: "'Vingt' significa:", hi: "'Vingt' का अर्थ:", ar: "'Vingt' تعني:" },
        opts: ['15','18','19','20'], ans: 3 },
      { q: { en: "'Trois' is pronounced:", pa: "'Trois' ਦਾ ਉਚਾਰਨ:", es: "'Trois' se pronuncia:", hi: "'Trois' का उच्चारण:", ar: "نطق 'Trois':" },
        opts: ['TROH-ee','TWAH','TRWAH','TROYS'], ans: 1 },
    ],
  },

  'a1-3': {
    id: 'a1-3', moduleId: 'A1', icon: '🎨', xp: 25,
    title: { en: 'Colors', pa: 'ਰੰਗ', es: 'Colores', hi: 'रंग', ar: 'الألوان' },
    concept: {
      en: `In French, color adjectives come AFTER the noun — the opposite of English. They also must match the noun's gender: masculine nouns take the base form, feminine nouns usually add -e. Example: "un chat noir" (a black cat, masculine) vs "une robe noire" (a black dress, feminine). Some colors like "orange" and "rose" never change form.`,
      pa: `ਫ੍ਰੈਂਚ ਵਿੱਚ, ਰੰਗ ਵਿਸ਼ੇਸ਼ਣ ਨਾਂਵ ਤੋਂ ਬਾਅਦ ਆਉਂਦੇ ਹਨ — ਅੰਗਰੇਜ਼ੀ ਦੇ ਉਲਟ। ਉਹ ਨਾਂਵ ਦੇ ਲਿੰਗ ਨਾਲ ਵੀ ਮੇਲ ਖਾਂਦੇ ਹਨ: ਨਰਲਿੰਗ = ਅਧਾਰ ਰੂਪ, ਇਸਤਰੀਲਿੰਗ = ਅੰਤ ਵਿੱਚ -e ਜੋੜੋ।`,
      es: `En francés, los adjetivos de color van DESPUÉS del sustantivo. También deben concordar con el género del sustantivo: masculino = forma base, femenino = añadir -e. Ejemplo: "un chat noir" vs "une robe noire".`,
      hi: `फ्रेंच में, रंग विशेषण संज्ञा के बाद आते हैं — अंग्रेजी के विपरीत। वे संज्ञा के लिंग से भी मेल खाते हैं: पुल्लिंग = आधार रूप, स्त्रीलिंग = अंत में -e जोड़ें।`,
      ar: `في الفرنسية، صفات الألوان تأتي بعد الاسم — عكس الإنجليزية. يجب أن تتطابق مع جنس الاسم: المذكر = الصيغة الأساسية، المؤنث = إضافة -e.`,
    },
    vocab: [
      { fr: 'rouge',              ph: 'ROOZH',              en: 'Red',    pa: 'ਲਾਲ',    es: 'Rojo',     hi: 'लाल',     ar: 'أحمر' },
      { fr: 'bleu / bleue',       ph: 'BLUH',               en: 'Blue',   pa: 'ਨੀਲਾ',   es: 'Azul',     hi: 'नीला',    ar: 'أزرق' },
      { fr: 'vert / verte',       ph: 'VEHR / VEHRT',       en: 'Green',  pa: 'ਹਰਾ',    es: 'Verde',    hi: 'हरा',     ar: 'أخضر' },
      { fr: 'jaune',              ph: 'ZHOHN',              en: 'Yellow', pa: 'ਪੀਲਾ',   es: 'Amarillo', hi: 'पीला',    ar: 'أصفر' },
      { fr: 'blanc / blanche',    ph: 'BLAHN / BLAHNSH',    en: 'White',  pa: 'ਚਿੱਟਾ',  es: 'Blanco',   hi: 'सफेद',    ar: 'أبيض' },
      { fr: 'noir / noire',       ph: 'NWAHR',              en: 'Black',  pa: 'ਕਾਲਾ',   es: 'Negro',    hi: 'काला',    ar: 'أسود' },
      { fr: 'orange',             ph: 'oh-RAHNZH',          en: 'Orange', pa: 'ਸੰਤਰੀ',  es: 'Naranja',  hi: 'नारंगी',  ar: 'برتقالي' },
      { fr: 'rose',               ph: 'ROHZ',               en: 'Pink',   pa: 'ਗੁਲਾਬੀ', es: 'Rosa',     hi: 'गुलाबी',  ar: 'وردي' },
      { fr: 'violet / violette',  ph: 'vee-oh-LAY',         en: 'Purple', pa: 'ਜਾਮਨੀ',  es: 'Morado',   hi: 'बैंगनी',  ar: 'بنفسجي' },
      { fr: 'gris / grise',       ph: 'GREE / GREEZ',       en: 'Gray',   pa: 'ਸਲੇਟੀ',  es: 'Gris',     hi: 'भूरा/ग्रे', ar: 'رمادي' },
    ],
    exercises: [
      { q: { en: "'Rouge' means:", pa: "'Rouge' ਦਾ ਮਤਲਬ:", es: "'Rouge' significa:", hi: "'Rouge' का अर्थ:", ar: "'Rouge' تعني:" },
        opts: ['Blue','Green','Red','Yellow'], ans: 2 },
      { q: { en: "'Black' in French is:", pa: "ਫ੍ਰੈਂਚ ਵਿੱਚ 'ਕਾਲਾ':", es: "'Negro' en francés:", hi: "फ्रेंच में 'काला':", ar: "'أسود' بالفرنسية:" },
        opts: ['blanc','gris','noir','bleu'], ans: 2 },
      { q: { en: "Colors in French come ___ the noun", pa: "ਫ੍ਰੈਂਚ ਵਿੱਚ ਰੰਗ ਨਾਂਵ ___ ਆਉਂਦੇ ਹਨ", es: "Los colores van ___ del sustantivo", hi: "फ्रेंच में रंग संज्ञा के ___ आते हैं", ar: "الألوان تأتي ___ الاسم" },
        opts: ['before','after','around','without'], ans: 1 },
      { q: { en: "'Jaune' means:", pa: "'Jaune' ਦਾ ਮਤਲਬ:", es: "'Jaune' significa:", hi: "'Jaune' का अर्थ:", ar: "'Jaune' تعني:" },
        opts: ['Pink','Yellow','Green','Orange'], ans: 1 },
      { q: { en: "Feminine of 'vert' is:", pa: "'Vert' ਦਾ ਇਸਤਰੀਲਿੰਗ:", es: "Femenino de 'vert':", hi: "'Vert' का स्त्रीलिंग:", ar: "مؤنث 'vert':" },
        opts: ['verts','verde','verte','vertu'], ans: 2 },
    ],
  },

  'a1-4': {
    id: 'a1-4', moduleId: 'A1', icon: '👨‍👩‍👧', xp: 30,
    title: { en: 'Family Members', pa: 'ਪਰਿਵਾਰ', es: 'La familia', hi: 'परिवार', ar: 'العائلة' },
    concept: {
      en: `French family nouns have grammatical gender — every noun is either masculine (le/un) or feminine (la/une). Possessives also change: "mon père" (my father — masculine) vs "ma mère" (my mother — feminine). This gender system applies to ALL French nouns, not just family words, so mastering it here builds a foundation for everything ahead.`,
      pa: `ਫ੍ਰੈਂਚ ਪਰਿਵਾਰਕ ਨਾਂਵਾਂ ਵਿੱਚ ਵਿਆਕਰਨਿਕ ਲਿੰਗ ਹੈ। "Mon père" (ਮੇਰੇ ਪਿਤਾ — ਨਰਲਿੰਗ) ਬਨਾਮ "ma mère" (ਮੇਰੀ ਮਾਤਾ — ਇਸਤਰੀਲਿੰਗ)। ਇਹ ਲਿੰਗ ਪ੍ਰਣਾਲੀ ਸਾਰੇ ਫ੍ਰੈਂਚ ਨਾਂਵਾਂ ਤੇ ਲਾਗੂ ਹੁੰਦੀ ਹੈ।`,
      es: `Los sustantivos de familia tienen género gramatical. Posesivos: "mon père" (mi padre — masculino) vs "ma mère" (mi madre — femenino). Este sistema de género aplica a TODOS los sustantivos franceses.`,
      hi: `फ्रेंच पारिवारिक संज्ञाओं में व्याकरणिक लिंग है। "Mon père" (मेरे पिता — पुल्लिंग) बनाम "ma mère" (मेरी माँ — स्त्रीलिंग)। यह लिंग प्रणाली सभी फ्रेंच संज्ञाओं पर लागू होती है।`,
      ar: `للأسماء العائلية الفرنسية جنس نحوي. الملكية: "mon père" (أبي — مذكر) مقابل "ma mère" (أمي — مؤنث). هذا النظام يطبق على جميع الأسماء الفرنسية.`,
    },
    vocab: [
      { fr: 'le père / la mère',      ph: 'luh PEHR / lah MEHR',   en: 'Father / Mother',      pa: 'ਪਿਤਾ / ਮਾਤਾ',         es: 'Padre / Madre',    hi: 'पिता / माँ',      ar: 'الأب / الأم' },
      { fr: 'le frère / la sœur',     ph: 'luh FREHR / lah SUR',   en: 'Brother / Sister',     pa: 'ਭਰਾ / ਭੈਣ',           es: 'Hermano / Hermana',hi: 'भाई / बहन',       ar: 'الأخ / الأخت' },
      { fr: 'le fils / la fille',     ph: 'luh FEES / lah FEE',    en: 'Son / Daughter',       pa: 'ਪੁੱਤਰ / ਧੀ',           es: 'Hijo / Hija',      hi: 'बेटा / बेटी',     ar: 'الابن / الابنة' },
      { fr: 'le grand-père',          ph: 'luh grahn-PEHR',        en: 'Grandfather',          pa: 'ਦਾਦਾ / ਨਾਨਾ',         es: 'Abuelo',           hi: 'दादा / नाना',     ar: 'الجد' },
      { fr: 'la grand-mère',          ph: 'lah grahn-MEHR',        en: 'Grandmother',          pa: 'ਦਾਦੀ / ਨਾਨੀ',         es: 'Abuela',           hi: 'दादी / नानी',     ar: 'الجدة' },
      { fr: 'le mari / la femme',     ph: 'luh mah-REE / lah FAM', en: 'Husband / Wife',       pa: 'ਪਤੀ / ਪਤਨੀ',           es: 'Esposo / Esposa',  hi: 'पति / पत्नी',     ar: 'الزوج / الزوجة' },
      { fr: "l'oncle / la tante",     ph: 'LOHN-kluh / lah TAHNT', en: 'Uncle / Aunt',         pa: 'ਚਾਚਾ / ਚਾਚੀ',         es: 'Tío / Tía',        hi: 'चाचा / चाची',     ar: 'العم / العمة' },
      { fr: 'Ma famille est grande',  ph: 'mah fah-MEE ay GRAHND', en: 'My family is big',     pa: 'ਮੇਰਾ ਪਰਿਵਾਰ ਵੱਡਾ ਹੈ',  es: 'Mi familia es grande', hi: 'मेरा परिवार बड़ा है', ar: 'عائلتي كبيرة' },
    ],
    exercises: [
      { q: { en: "'La mère' means:", pa: "'La mère' ਦਾ ਮਤਲਬ:", es: "'La mère' significa:", hi: "'La mère' का अर्थ:", ar: "'La mère' تعني:" },
        opts: ['The father','The mother','The sister','The daughter'], ans: 1 },
      { q: { en: "'Le frère' means:", pa: "'Le frère' ਦਾ ਮਤਲਬ:", es: "'Le frère' significa:", hi: "'Le frère' का अर्थ:", ar: "'Le frère' تعني:" },
        opts: ['Sister','Father','Brother','Son'], ans: 2 },
      { q: { en: "'La fille' can mean:", pa: "'La fille' ਦਾ ਮਤਲਬ ਹੋ ਸਕਦਾ ਹੈ:", es: "'La fille' puede significar:", hi: "'La fille' का अर्थ हो सकता है:", ar: "'La fille' تعني:" },
        opts: ['Son or boy','Daughter or girl','Mother or aunt','Sister or cousin'], ans: 1 },
      { q: { en: "'Grandfather' in French:", pa: "ਫ੍ਰੈਂਚ ਵਿੱਚ 'ਦਾਦਾ':", es: "'Abuelo' en francés:", hi: "फ्रेंच में 'दादा':", ar: "'الجد' بالفرنسية:" },
        opts: ['le père','le fils','le grand-père','le frère'], ans: 2 },
      { q: { en: "'Mon' is used with ___ nouns", pa: "'Mon' ___ ਨਾਂਵਾਂ ਨਾਲ", es: "'Mon' con sustantivos ___", hi: "'Mon' ___ संज्ञाओं के साथ", ar: "'Mon' مع الأسماء ___" },
        opts: ['feminine','masculine','plural','all'], ans: 1 },
    ],
  },

  // ─── A2 ───────────────────────────────────────────────────────────────────

  'a2-1': {
    id: 'a2-1', moduleId: 'A2', icon: '⚡', xp: 35,
    title: { en: 'Present Tense — ER Verbs', pa: 'ਵਰਤਮਾਨ ਕਾਲ — ER ਕ੍ਰਿਆਵਾਂ', es: 'Presente — Verbos ER', hi: 'वर्तमान काल — ER क्रियाएँ', ar: 'المضارع — أفعال ER' },
    concept: {
      en: `Regular -ER verbs are the most common French verbs. To conjugate: remove -ER, then add the ending for the subject. Pattern: je → -e, tu → -es, il/elle → -e, nous → -ons, vous → -ez, ils/elles → -ent. Example with "parler" (to speak): je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent. Master this and you can use hundreds of French verbs.`,
      pa: `ਨਿਯਮਤ -ER ਕ੍ਰਿਆਵਾਂ ਸਭ ਤੋਂ ਆਮ ਫ੍ਰੈਂਚ ਕ੍ਰਿਆਵਾਂ ਹਨ। ਸੰਜੋਗ ਕਰਨ ਲਈ: -ER ਹਟਾਓ, ਫਿਰ ਵਿਸ਼ੇ ਲਈ ਅੰਤ ਜੋੜੋ। je→-e, tu→-es, il/elle→-e, nous→-ons, vous→-ez, ils/elles→-ent.`,
      es: `Los verbos -ER regulares son los más comunes. Para conjugar: quita -ER y añade la terminación del sujeto: je→-e, tu→-es, il/elle→-e, nous→-ons, vous→-ez, ils/elles→-ent.`,
      hi: `नियमित -ER क्रियाएं सबसे सामान्य फ्रेंच क्रियाएं हैं। संयुग्मित करने के लिए: -ER हटाएं, फिर विषय के लिए अंत जोड़ें: je→-e, tu→-es, il/elle→-e, nous→-ons, vous→-ez, ils/elles→-ent.`,
      ar: `الأفعال المنتظمة -ER هي الأكثر شيوعاً. للتصريف: أزل -ER ثم أضف اللاحقة المناسبة: je→-e, tu→-es, il/elle→-e, nous→-ons, vous→-ez, ils/elles→-ent.`,
    },
    vocab: [
      { fr: 'parler → je parle',         ph: 'par-LAY / zhuh PARL',    en: 'to speak → I speak',    pa: 'ਬੋਲਣਾ → ਮੈਂ ਬੋਲਦਾ ਹਾਂ', es: 'hablar → yo hablo',      hi: 'बोलना → मैं बोलता हूँ',   ar: 'يتحدث → أتحدث' },
      { fr: 'manger → je mange',         ph: 'mahn-ZHAY / zhuh MAHNZH',en: 'to eat → I eat',        pa: 'ਖਾਣਾ → ਮੈਂ ਖਾਂਦਾ ਹਾਂ',   es: 'comer → yo como',       hi: 'खाना → मैं खाता हूँ',     ar: 'يأكل → آكل' },
      { fr: "habiter → j'habite",        ph: 'ah-bee-TAY',             en: 'to live → I live',      pa: 'ਰਹਿਣਾ → ਮੈਂ ਰਹਿੰਦਾ ਹਾਂ',  es: 'vivir → yo vivo',       hi: 'रहना → मैं रहता हूँ',     ar: 'يسكن → أسكن' },
      { fr: 'travailler → je travaille', ph: 'trah-vah-YAY',           en: 'to work → I work',      pa: 'ਕੰਮ ਕਰਨਾ → ਮੈਂ ਕੰਮ ਕਰਦਾ',es: 'trabajar → yo trabajo', hi: 'काम करना → मैं काम करता', ar: 'يعمل → أعمل' },
      { fr: "aimer → j'aime",           ph: 'ay-MAY / zheym',         en: 'to like/love → I like', pa: 'ਪਸੰਦ ਕਰਨਾ → ਮੈਨੂੰ ਪਸੰਦ',  es: 'gustar/amar → me gusta',hi: 'पसंद करना → मुझे पसंद',  ar: 'يحب → أحب' },
      { fr: "étudier → j'étudie",       ph: 'ay-tood-YAY',            en: 'to study → I study',    pa: 'ਪੜ੍ਹਨਾ → ਮੈਂ ਪੜ੍ਹਦਾ ਹਾਂ',  es: 'estudiar → yo estudio', hi: 'पढ़ना → मैं पढ़ता हूँ',    ar: 'يدرس → أدرس' },
      { fr: 'Nous parlons français',     ph: 'noo par-LOH frahn-SAY',  en: 'We speak French',       pa: 'ਅਸੀਂ ਫ੍ਰੈਂਚ ਬੋਲਦੇ ਹਾਂ',  es: 'Hablamos francés',      hi: 'हम फ्रेंच बोलते हैं',    ar: 'نتحدث الفرنسية' },
      { fr: "Vous habitez où?",          ph: 'voo za-bee-TAY oo',      en: 'Where do you live? (formal)', pa: 'ਤੁਸੀਂ ਕਿੱਥੇ ਰਹਿੰਦੇ ਹੋ?', es: '¿Dónde viven?', hi: 'आप कहाँ रहते हैं?', ar: 'أين تسكن؟' },
    ],
    exercises: [
      { q: { en: "Complete: 'Je ___ français' (parler)", pa: "'Je ___ français' ਪੂਰਾ ਕਰੋ", es: "Completa: 'Je ___ français'", hi: "पूरा करें: 'Je ___ français'", ar: "أكمل: 'Je ___ français'" },
        opts: ['parles','parle','parlons','parlez'], ans: 1 },
      { q: { en: "'J'habite' means:", pa: "'J'habite' ਦਾ ਮਤਲਬ:", es: "'J'habite' significa:", hi: "'J'habite' का अर्थ:", ar: "'J'habite' تعني:" },
        opts: ['I work','I eat','I live','I love'], ans: 2 },
      { q: { en: "The 'nous' ending for -ER verbs is:", pa: "-ER ਕ੍ਰਿਆਵਾਂ ਦਾ 'nous' ਅੰਤ:", es: "La terminación 'nous' es:", hi: "-ER क्रियाओं का 'nous' अंत:", ar: "لاحقة 'nous' للأفعال -ER:" },
        opts: ['-es','-ez','-ons','-ent'], ans: 2 },
      { q: { en: "'Vous' form of 'manger' is:", pa: "'Manger' ਦਾ 'vous' ਰੂਪ:", es: "Forma 'vous' de 'manger':", hi: "'Manger' का 'vous' रूप:", ar: "صيغة 'vous' من 'manger':" },
        opts: ['mangez','mangent','mangeons','manges'], ans: 0 },
      { q: { en: "'J'étudie' means:", pa: "'J'étudie' ਦਾ ਮਤਲਬ:", es: "'J'étudie' significa:", hi: "'J'étudie' का अर्थ:", ar: "'J'étudie' تعني:" },
        opts: ['I work','I speak','I study','I live'], ans: 2 },
    ],
  },

  'a2-2': {
    id: 'a2-2', moduleId: 'A2', icon: '🕐', xp: 35,
    title: { en: 'Telling Time & Daily Routine', pa: 'ਸਮਾਂ ਅਤੇ ਰੋਜ਼ਾਨਾ ਕਾਰਜ', es: 'La hora y la rutina', hi: 'समय और दैनिक दिनचर्या', ar: 'الوقت والروتين اليومي' },
    concept: {
      en: `French uses "Il est…" to tell time (It is…). For exact hours: "Il est deux heures" (It is 2 o'clock). Half past = "et demie," quarter past = "et quart," quarter to = "moins le quart." For AM/PM: "du matin" (morning), "de l'après-midi" (afternoon), "du soir" (evening). This is essential for scheduling appointments in Canada.`,
      pa: `ਫ੍ਰੈਂਚ ਵਿੱਚ ਸਮਾਂ ਦੱਸਣ ਲਈ "Il est…" ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ। "Il est deux heures" = 2 ਵੱਜੇ ਹਨ। ਸਾਢੇ = et demie, ਪੌਣੇ ਵੱਜੇ = et quart, ਪੰਜ ਘੱਟ = moins le quart.`,
      es: `Se usa "Il est…" para decir la hora. "Il est deux heures" (Son las 2). Et demie = y media, et quart = y cuarto, moins le quart = menos cuarto. Esencial para citas en Canadá.`,
      hi: `फ्रेंच में समय बताने के लिए "Il est…" का उपयोग होता है। "Il est deux heures" = 2 बजे हैं। Et demie = साढ़े, et quart = सवा, moins le quart = पौने।`,
      ar: `تُستخدم "Il est…" للإخبار عن الوقت. "Il est deux heures" = الساعة الثانية. et demie = والنصف، et quart = والربع، moins le quart = إلا الربع.`,
    },
    vocab: [
      { fr: 'Quelle heure est-il?',  ph: 'kel-UR ay-TEEL',      en: 'What time is it?',        pa: 'ਕਿੰਨੇ ਵੱਜੇ ਹਨ?',           es: '¿Qué hora es?',      hi: 'कितने बजे हैं?',     ar: 'كم الساعة؟' },
      { fr: 'Il est huit heures',    ph: 'eel ay WEET ur',       en: 'It is 8 o\'clock',        pa: '8 ਵੱਜੇ ਹਨ',                es: 'Son las ocho',       hi: '8 बजे हैं',          ar: 'الساعة الثامنة' },
      { fr: 'Il est midi / minuit',  ph: 'mee-DEE / mee-NWEE',  en: 'It is noon / midnight',   pa: 'ਦੁਪਹਿਰ / ਅੱਧੀ ਰਾਤ',        es: 'Es mediodía / noche',hi: 'दोपहर / आधी रात',   ar: 'الظهر / منتصف الليل' },
      { fr: 'et demie / et quart',   ph: 'ay duh-MEE / ay KAR',  en: 'half past / quarter past',pa: 'ਸਾਢੇ / ਪੌਣੇ ਵੱਜੇ',          es: 'y media / y cuarto', hi: 'साढ़े / सवा',         ar: 'والنصف / والربع' },
      { fr: 'le matin / le soir',    ph: 'luh mah-TAN / SWAHR',  en: 'morning / evening',       pa: 'ਸਵੇਰੇ / ਸ਼ਾਮ',              es: 'mañana / tarde-noche',hi: 'सुबह / शाम',         ar: 'الصباح / المساء' },
      { fr: 'Je me lève à 7h',       ph: 'zhuh muh LEV ah set',  en: 'I get up at 7am',         pa: 'ਮੈਂ 7 ਵਜੇ ਉੱਠਦਾ ਹਾਂ',       es: 'Me levanto a las 7', hi: 'मैं 7 बजे उठता हूँ', ar: 'أستيقظ في السابعة' },
      { fr: "J'arrive au bureau",    ph: "zhah-REEV oh byoo-ROH", en: 'I arrive at the office',  pa: 'ਮੈਂ ਦਫ਼ਤਰ ਪਹੁੰਚਦਾ ਹਾਂ',      es: 'Llego a la oficina', hi: 'मैं ऑफिस पहुँचता हूँ', ar: 'أصل إلى المكتب' },
    ],
    exercises: [
      { q: { en: "'Quelle heure est-il?' means:", pa: "'Quelle heure est-il?' ਦਾ ਮਤਲਬ:", es: "'Quelle heure est-il?' significa:", hi: "'Quelle heure est-il?' का अर्थ:", ar: "'Quelle heure est-il?' تعني:" },
        opts: ['What day is it?','What time is it?','Where are you?','How are you?'], ans: 1 },
      { q: { en: "'Il est midi' means:", pa: "'Il est midi' ਦਾ ਮਤਲਬ:", es: "'Il est midi' significa:", hi: "'Il est midi' का अर्थ:", ar: "'Il est midi' تعني:" },
        opts: ['It is midnight','It is 3pm','It is noon','It is evening'], ans: 2 },
      { q: { en: "'Et demie' means:", pa: "'Et demie' ਦਾ ਮਤਲਬ:", es: "'Et demie' significa:", hi: "'Et demie' का अर्थ:", ar: "'Et demie' تعني:" },
        opts: ['quarter past','half past','quarter to','on the hour'], ans: 1 },
      { q: { en: "'Le matin' refers to:", pa: "'Le matin' ਦਾ ਮਤਲਬ:", es: "'Le matin' es:", hi: "'Le matin' का अर्थ:", ar: "'Le matin' يشير إلى:" },
        opts: ['afternoon','evening','night','morning'], ans: 3 },
      { q: { en: "'Je me lève' means:", pa: "'Je me lève' ਦਾ ਮਤਲਬ:", es: "'Je me lève' significa:", hi: "'Je me lève' का अर्थ:", ar: "'Je me lève' تعني:" },
        opts: ['I sleep','I eat','I get up','I work'], ans: 2 },
    ],
  },
};

export const TEF_SECTIONS = [
  {
    id: 'reading', icon: '📖', color: 'blue',
    title: { en: 'Reading Comprehension', pa: 'ਪੜ੍ਹਨ ਦੀ ਸਮਝ', es: 'Comprensión lectora', hi: 'पठन बोध', ar: 'فهم المقروء' },
    desc:  { en: 'Timed passages with multiple-choice questions', pa: 'ਸਮਾਂਬੱਧ ਪੈਸੇਜ ਅਤੇ ਬਹੁਵਿਕਲਪੀ ਪ੍ਰਸ਼ਨ', es: 'Textos con preguntas de opción múltiple', hi: 'बहुविकल्पीय प्रश्नों के साथ गद्यांश', ar: 'نصوص مع أسئلة متعددة الخيارات' },
    passage: `Le Canada est un pays situé en Amérique du Nord. C'est le deuxième plus grand pays du monde par superficie totale. Le Canada est connu pour ses vastes paysages naturels, sa diversité culturelle exceptionnelle et son système de santé universel. Les deux langues officielles du Canada sont l'anglais et le français. Le français est particulièrement important dans la province de Québec et dans la région d'Ottawa. Pour obtenir la citoyenneté canadienne ou pour travailler dans certains secteurs, il est souvent nécessaire de démontrer une compétence en français au niveau CLB 7 ou supérieur.`,
    questions: [
      { q: { en: 'Where is Canada located?', pa: 'ਕੈਨੇਡਾ ਕਿੱਥੇ ਹੈ?', es: '¿Dónde está Canadá?', hi: 'कनाडा कहाँ है?', ar: 'أين يقع كندا؟' },
        opts: ['South America','North America','Europe','Asia'], ans: 1 },
      { q: { en: 'How many official languages does Canada have?', pa: 'ਕੈਨੇਡਾ ਦੀਆਂ ਕਿੰਨੀਆਂ ਸਰਕਾਰੀ ਭਾਸ਼ਾਵਾਂ ਹਨ?', es: '¿Cuántas lenguas oficiales?', hi: 'कितनी आधिकारिक भाषाएँ?', ar: 'كم عدد اللغات الرسمية؟' },
        opts: ['1','2','3','4'], ans: 1 },
      { q: { en: 'What level of French is often required for citizenship?', pa: 'ਨਾਗਰਿਕਤਾ ਲਈ ਕਿਹੜਾ ਫ੍ਰੈਂਚ ਪੱਧਰ ਜ਼ਰੂਰੀ ਹੈ?', es: '¿Qué nivel de francés se requiere para la ciudadanía?', hi: 'नागरिकता के लिए कौन सा स्तर चाहिए?', ar: 'ما المستوى المطلوب للجنسية؟' },
        opts: ['CLB 4','CLB 5','CLB 7','CLB 9'], ans: 2 },
    ],
  },
  {
    id: 'writing', icon: '✍️', color: 'purple',
    title: { en: 'Writing Practice', pa: 'ਲਿਖਣ ਅਭਿਆਸ', es: 'Práctica escrita', hi: 'लेखन अभ्यास', ar: 'ممارسة الكتابة' },
    desc:  { en: 'Formal writing tasks with AI feedback', pa: 'ਰਸਮੀ ਲਿਖਣ ਕਾਰਜ ਅਤੇ AI ਫੀਡਬੈਕ', es: 'Tareas formales con retroalimentación IA', hi: 'AI फीडबैक के साथ औपचारिक लेखन', ar: 'مهام كتابية رسمية مع تغذية راجعة بالذكاء الاصطناعي' },
    prompts: [
      { en: 'Write a formal email (150–200 words) to your employer requesting two days off to attend French language classes. Include: the reason, the specific dates, and how your work responsibilities will be covered during your absence.',
        pa: 'ਆਪਣੇ ਮਾਲਕ ਨੂੰ ਇੱਕ ਰਸਮੀ ਈਮੇਲ (150-200 ਸ਼ਬਦ) ਲਿਖੋ ਜਿਸ ਵਿੱਚ ਫ੍ਰੈਂਚ ਭਾਸ਼ਾ ਦੀਆਂ ਕਲਾਸਾਂ ਲਈ ਦੋ ਦਿਨ ਦੀ ਛੁੱਟੀ ਮੰਗੀ ਗਈ ਹੋਵੇ।',
        es: 'Escribe un correo formal (150-200 palabras) a tu empleador solicitando dos días para asistir a clases de francés. Incluye: razón, fechas específicas, y cómo se cubrirá tu trabajo.',
        hi: 'अपने नियोक्ता को एक औपचारिक ईमेल (150-200 शब्द) लिखें जिसमें फ्रेंच भाषा की कक्षाओं के लिए दो दिन की छुट्टी मांगी गई हो।',
        ar: 'اكتب بريداً إلكترونياً رسمياً (150-200 كلمة) لصاحب العمل تطلب فيه يومين إجازة لحضور دروس اللغة الفرنسية.' },
    ],
  },
  {
    id: 'listening', icon: '🎧', color: 'green',
    title: { en: 'Listening Comprehension', pa: 'ਸੁਣਨ ਦੀ ਸਮਝ', es: 'Comprensión auditiva', hi: 'श्रवण बोध', ar: 'فهم المسموع' },
    desc:  { en: 'Audio passages with comprehension questions — coming soon', pa: 'ਆਡੀਓ ਸਮਝ ਪ੍ਰਸ਼ਨ — ਜਲਦੀ ਆ ਰਹੇ ਹਨ', es: 'Pasajes de audio — próximamente', hi: 'ऑडियो समझ — जल्द आ रहा है', ar: 'مقاطع صوتية — قريباً' },
    comingSoon: true,
  },
  {
    id: 'speaking', icon: '🎤', color: 'amber',
    title: { en: 'Speaking Practice', pa: 'ਬੋਲਣ ਦਾ ਅਭਿਆਸ', es: 'Práctica oral', hi: 'बोलने का अभ्यास', ar: 'ممارسة الكلام' },
    desc:  { en: 'Structured prompts for oral exam simulation — coming soon', pa: 'ਮੌਖਿਕ ਪ੍ਰੀਖਿਆ ਸਿਮੂਲੇਸ਼ਨ — ਜਲਦੀ ਆ ਰਹੇ ਹਨ', es: 'Simulación del examen oral — próximamente', hi: 'मौखिक परीक्षा सिमुलेशन — जल्द', ar: 'محاكاة الامتحان الشفهي — قريباً' },
    comingSoon: true,
  },
];
