// lib/data.js — All lesson content and module structure
export const MODULES = [
  {
    id: 'A1', icon: '🌱', color: 'a1', locked: false,
    label: { en: 'A1 — Beginner', pa: 'A1 — ਸ਼ੁਰੂਆਤੀ', es: 'A1 — Principiante', hi: 'A1 — शुरुआती', ar: 'A1 — مبتدئ' },
    desc: { en: 'Greetings, numbers, colors, family — zero to first conversations', pa: 'ਸ਼ੁਭਕਾਮਨਾਵਾਂ, ਨੰਬਰ, ਰੰਗ, ਪਰਿਵਾਰ', es: 'Saludos, números, colores, familia', hi: 'अभिवादन, संख्याएँ, रंग, परिवार', ar: 'تحيات وأرقام وألوان وعائلة' },
    lessons: ['a1-1', 'a1-2', 'a1-3', 'a1-4', 'a1-5', 'a1-6'],
  },
  {
    id: 'A2', icon: '📗', color: 'a2', locked: false,
    label: { en: 'A2 — Elementary', pa: 'A2 — ਮੁੱਢਲਾ', es: 'A2 — Elemental', hi: 'A2 — प्रारंभिक', ar: 'A2 — ابتدائي' },
    desc: { en: 'Present tense verbs, daily routines, time, descriptions', pa: 'ਵਰਤਮਾਨ ਕਾਲ, ਰੋਜ਼ਾਨਾ ਜ਼ਿੰਦਗੀ, ਸਮਾਂ', es: 'Presente, rutina, hora, descripciones', hi: 'वर्तमान काल, दैनिक दिनचर्या, समय', ar: 'المضارع والروتين والوقت' },
    lessons: ['a2-1', 'a2-2', 'a2-3', 'a2-4', 'a2-5'],
  },
  {
    id: 'B1', icon: '📘', color: 'b1', locked: false,
    label: { en: 'B1 — Intermediate', pa: 'B1 — ਵਿਚਕਾਰਲਾ', es: 'B1 — Intermedio', hi: 'B1 — मध्यवर्ती', ar: 'B1 — متوسط' },
    desc: { en: 'Past tense, opinions, work, health, travel — real-world French', pa: 'ਭੂਤ ਕਾਲ, ਵਿਚਾਰ, ਕਿੱਤਾ', es: 'Pasado, opiniones, trabajo', hi: 'भूत काल, राय, कार्यस्थल', ar: 'الماضي والآراء والعمل' },
    lessons: ['b1-1', 'b1-2', 'b1-3', 'b1-4', 'b1-5'],
  },
  {
    id: 'B2', icon: '📙', color: 'b2', locked: false,
    label: { en: 'B2 — Upper Intermediate', pa: 'B2 — ਉੱਚ ਵਿਚਕਾਰਲਾ', es: 'B2 — Intermedio alto', hi: 'B2 — उच्च मध्यवर्ती', ar: 'B2 — متوسط متقدم' },
    desc: { en: 'Complex grammar, nuanced speech, advanced vocabulary for TEF', pa: 'ਗੁੰਝਲਦਾਰ ਵਿਆਕਰਨ, ਉੱਚ ਸ਼ਬਦਾਵਲੀ', es: 'Gramática compleja, vocabulario avanzado', hi: 'जटिल व्याकरण, उन्नत शब्दावली', ar: 'قواعد معقدة ومفردات متقدمة' },
    lessons: ['b2-1', 'b2-2', 'b2-3', 'b2-4'],
  },
  {
    id: 'TEF', icon: '🏆', color: 'tef', locked: false,
    label: { en: 'TEF Prep — CLB 7+', pa: 'TEF ਤਿਆਰੀ — CLB 7+', es: 'Preparación TEF — CLB 7+', hi: 'TEF तैयारी — CLB 7+', ar: 'التحضير لـ TEF' },
    desc: { en: 'Full TEF exam simulation — reading, writing, listening, speaking', pa: 'ਪੂਰੀ TEF ਪ੍ਰੀਖਿਆ ਤਿਆਰੀ', es: 'Preparación completa para el TEF', hi: 'पूर्ण TEF परीक्षा तैयारी', ar: 'التحضير الكامل لامتحان TEF' },
    lessons: ['tef-1', 'tef-2', 'tef-3', 'tef-4'],
  },
]

export const LESSONS = {'a1-1': {
    id: 'a1-1', moduleId: 'A1',
    title: { en: 'Greetings & Introductions', pa: 'ਸ਼ੁਭਕਾਮਨਾਵਾਂ', es: 'Saludos', hi: 'अभिवादन', ar: 'التحيات' },
    xp: 20,
    vocab: [
      { fr: 'Bonjour', en: 'Hello / Good morning', example: 'Bonjour, je m\'appelle Marie.' },
      { fr: 'Bonsoir', en: 'Good evening', example: 'Bonsoir madame, comment allez-vous ?' },
      { fr: 'Bonne nuit', en: 'Good night', example: 'Bonne nuit, à demain !' },
      { fr: 'Salut', en: 'Hi (informal)', example: 'Salut, ça va ?' },
      { fr: 'Au revoir', en: 'Goodbye', example: 'Au revoir, à bientôt !' },
      { fr: 'À bientôt', en: 'See you soon', example: 'À bientôt, bonne journée !' },
      { fr: 'Je m\'appelle', en: 'My name is', example: 'Je m\'appelle Jean-Pierre.' },
      { fr: 'Comment vous appelez-vous ?', en: 'What is your name? (formal)', example: 'Bonjour, comment vous appelez-vous ?' },
      { fr: 'Enchanté(e)', en: 'Nice to meet you', example: 'Enchanté de faire votre connaissance.' },
      { fr: 'Comment allez-vous ?', en: 'How are you? (formal)', example: 'Bonjour monsieur, comment allez-vous ?' },
      { fr: 'Ça va ?', en: 'How\'s it going?', example: 'Ça va ? — Oui, ça va bien merci !' },
      { fr: 'Très bien', en: 'Very well', example: 'Je vais très bien, merci.' },
      { fr: 'Pas mal', en: 'Not bad', example: 'Pas mal, et toi ?' },
      { fr: 'Comme ci comme ça', en: 'So-so', example: 'Comme ci comme ça, j\'ai beaucoup de travail.' },
      { fr: 'Merci', en: 'Thank you', example: 'Merci beaucoup pour votre aide.' },
      { fr: 'De rien', en: 'You\'re welcome', example: 'De rien, c\'est avec plaisir !' },
      { fr: 'S\'il vous plaît', en: 'Please (formal)', example: 'Un café, s\'il vous plaît.' },
      { fr: 'Excusez-moi', en: 'Excuse me (formal)', example: 'Excusez-moi, où est la gare ?' },
      { fr: 'Je suis', en: 'I am', example: 'Je suis canadien. Je suis étudiant.' },
      { fr: 'J\'habite à', en: 'I live in', example: 'J\'habite à Montréal.' },
    ],
    grammar: {
      title: 'Subject Pronouns & Être (to be)',
      explanation: 'In French, every sentence needs a subject pronoun. The verb être (to be) is the most important verb to learn first.',
      points: [
        'Je = I | Tu = You (informal) | Il/Elle = He/She',
        'Nous = We | Vous = You (formal/plural) | Ils/Elles = They',
        'Je suis, Tu es, Il/Elle est, Nous sommes, Vous êtes, Ils/Elles sont',
        'Use vous with strangers, teachers, and in professional settings',
        'Use tu with friends, family, and children',
      ],
      examples: [
        'Je suis étudiant. (I am a student.)',
        'Tu es canadien ? (Are you Canadian?)',
        'Elle est professeure. (She is a teacher.)',
        'Nous sommes à Montréal. (We are in Montreal.)',
        'Vous êtes médecin ? (Are you a doctor?)',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you say "Good evening" in French?', options: ['Bonjour', 'Bonsoir', 'Bonne nuit', 'Salut'], answer: 1 },
      { type: 'mcq', question: 'Which is the formal way to say "How are you?"', options: ['Ça va ?', 'Comment vas-tu ?', 'Comment allez-vous ?', 'T\'as le moral ?'], answer: 2 },
      { type: 'mcq', question: 'What does "Enchanté" mean?', options: ['Goodbye', 'Thank you', 'Nice to meet you', 'Excuse me'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Je ___ étudiant."', options: ['es', 'est', 'suis', 'sommes'], answer: 2 },
      { type: 'mcq', question: 'Which is informal for "you"?', options: ['vous', 'tu', 'il', 'on'], answer: 1 },
      { type: 'mcq', question: 'How do you say "My name is" in French?', options: ['Je suis', 'Je m\'appelle', 'J\'habite', 'Je viens'], answer: 1 },
      { type: 'mcq', question: 'What does "De rien" mean?', options: ['Thank you', 'Please', 'You\'re welcome', 'Excuse me'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Nous ___ à Montréal."', options: ['est', 'suis', 'sommes', 'êtes'], answer: 2 },
    ]
  },

  'a1-2': {
    id: 'a1-2', moduleId: 'A1',
    title: { en: 'Numbers 0–1000 & Beyond', pa: 'ਨੰਬਰ 0-1000', es: 'Números', hi: 'संख्याएँ', ar: 'الأرقام' },
    xp: 25,
    vocab: [
      { fr: 'zéro', en: '0', example: 'Mon numéro commence par zéro.' },
      { fr: 'un / une', en: '1', example: 'J\'ai un frère et une sœur.' },
      { fr: 'deux', en: '2', example: 'Il y a deux cafés ici.' },
      { fr: 'trois', en: '3', example: 'J\'ai trois enfants.' },
      { fr: 'quatre', en: '4', example: 'Il est quatre heures.' },
      { fr: 'cinq', en: '5', example: 'Cinq personnes attendent.' },
      { fr: 'six', en: '6', example: 'Six mois de travail.' },
      { fr: 'sept', en: '7', example: 'Sept jours par semaine.' },
      { fr: 'huit', en: '8', example: 'Huit heures du matin.' },
      { fr: 'neuf', en: '9', example: 'Neuf élèves dans la classe.' },
      { fr: 'dix', en: '10', example: 'Dix euros, s\'il vous plaît.' },
      { fr: 'vingt', en: '20', example: 'Vingt minutes de marche.' },
      { fr: 'trente', en: '30', example: 'Trente jours dans un mois.' },
      { fr: 'quarante', en: '40', example: 'Quarante heures par semaine.' },
      { fr: 'cinquante', en: '50', example: 'Cinquante pour cent.' },
      { fr: 'soixante', en: '60', example: 'Soixante secondes.' },
      { fr: 'soixante-dix', en: '70', example: 'Soixante-dix ans — un grand âge !' },
      { fr: 'quatre-vingts', en: '80', example: 'Quatre-vingts kilomètres.' },
      { fr: 'quatre-vingt-dix', en: '90', example: 'Quatre-vingt-dix pour cent.' },
      { fr: 'cent', en: '100', example: 'Cent dollars canadiens.' },
      { fr: 'mille', en: '1,000', example: 'Mille mercis !' },
      { fr: 'un million', en: '1,000,000', example: 'Un million de dollars.' },
      { fr: 'un milliard', en: '1,000,000,000', example: 'La population mondiale est de huit milliards.' },
    ],
    grammar: {
      title: 'How French Numbers Work',
      explanation: 'French numbers have unique patterns especially from 70-99. Understanding these patterns is essential for prices, phone numbers, and dates.',
      points: [
        '70 = soixante-dix (60+10), 71 = soixante et onze, 72 = soixante-douze...',
        '80 = quatre-vingts (4x20), 81 = quatre-vingt-un (no s when followed by number)',
        '90 = quatre-vingt-dix (4x20+10), 91 = quatre-vingt-onze...',
        'For 21, 31, 41, 51, 61 — use et: vingt et un, trente et un...',
        'For 81, 91 — NO et: quatre-vingt-un, quatre-vingt-onze',
        'Cents takes an s when exact (deux cents) but not when followed by more (deux cent cinq)',
      ],
      examples: [
        '75 = soixante-quinze',
        '83 = quatre-vingt-trois',
        '99 = quatre-vingt-dix-neuf',
        '200 = deux cents | 205 = deux cent cinq',
        '1500 = mille cinq cents',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you say 70 in French?', options: ['septante', 'soixante-dix', 'soixante-dixième', 'sept-dix'], answer: 1 },
      { type: 'mcq', question: 'How do you say 80 in French?', options: ['huitante', 'octante', 'quatre-vingts', 'quatre-vingt'], answer: 2 },
      { type: 'mcq', question: 'How do you say 92 in French?', options: ['nonante-deux', 'quatre-vingt-douze', 'quatre-vingt-deux', 'soixante-douze'], answer: 1 },
      { type: 'mcq', question: 'What is "vingt et un"?', options: ['20', '21', '31', '11'], answer: 1 },
      { type: 'mcq', question: 'How do you say 1000 in French?', options: ['cent', 'million', 'mille', 'milliard'], answer: 2 },
      { type: 'mcq', question: 'How do you say 200 in French?', options: ['deux cent', 'deux cents', 'deuxième cent', 'vingt cent'], answer: 1 },
      { type: 'mcq', question: 'What is "quatre-vingt-dix-neuf"?', options: ['89', '99', '79', '90'], answer: 1 },
      { type: 'mcq', question: 'How do you say one billion in French?', options: ['un million', 'un milliard', 'mille millions', 'cent mille'], answer: 1 },
    ]
  },

  'a1-3': {
    id: 'a1-3', moduleId: 'A1',
    title: { en: 'Colors, Descriptions & Adjectives', pa: 'ਰੰਗ ਅਤੇ ਵਰਣਨ', es: 'Colores y descripciones', hi: 'रंग और विवरण', ar: 'الألوان والأوصاف' },
    xp: 20,
    vocab: [
      { fr: 'rouge', en: 'red', example: 'La pomme est rouge.' },
      { fr: 'bleu(e)', en: 'blue', example: 'Le ciel est bleu.' },
      { fr: 'vert(e)', en: 'green', example: 'Les arbres sont verts.' },
      { fr: 'jaune', en: 'yellow', example: 'Le soleil est jaune.' },
      { fr: 'blanc(he)', en: 'white', example: 'La neige est blanche.' },
      { fr: 'noir(e)', en: 'black', example: 'Le chat est noir.' },
      { fr: 'gris(e)', en: 'grey', example: 'Le ciel est gris aujourd\'hui.' },
      { fr: 'rose', en: 'pink', example: 'Elle porte une robe rose.' },
      { fr: 'violet(te)', en: 'purple', example: 'Les lavandes sont violettes.' },
      { fr: 'marron', en: 'brown', example: 'J\'ai les cheveux marron.' },
      { fr: 'grand(e)', en: 'tall / big', example: 'Il est très grand.' },
      { fr: 'petit(e)', en: 'small / short', example: 'Elle est petite mais courageuse.' },
      { fr: 'beau / belle', en: 'beautiful', example: 'C\'est une belle ville.' },
      { fr: 'jeune', en: 'young', example: 'Il est encore jeune.' },
      { fr: 'vieux / vieille', en: 'old', example: 'C\'est un vieux quartier de Montréal.' },
      { fr: 'chaud(e)', en: 'hot / warm', example: 'Le café est chaud.' },
      { fr: 'froid(e)', en: 'cold', example: 'L\'hiver canadien est très froid.' },
      { fr: 'facile', en: 'easy', example: 'Ce n\'est pas facile !' },
      { fr: 'difficile', en: 'difficult', example: 'Le TEF est difficile sans préparation.' },
    ],
    grammar: {
      title: 'Adjective Agreement in French',
      explanation: 'In French, adjectives must agree in gender and number with the noun they describe.',
      points: [
        'Masculine singular: petit, grand, beau, vieux',
        'Feminine singular: add -e → petite, grande (beau→belle, vieux→vieille)',
        'Masculine plural: add -s → petits, grands',
        'Feminine plural: add -es → petites, grandes',
        'Adjectives usually come AFTER the noun in French',
        'BAGS adjectives come BEFORE: Beauty, Age, Goodness, Size',
      ],
      examples: [
        'Un chat noir / Une robe noire',
        'Un grand homme / Une grande femme',
        'Des chats noirs / Des robes noires',
        'Un beau garçon / Une belle fille',
        'C\'est une ville intéressante.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'What is the feminine form of "blanc"?', options: ['blanque', 'blanche', 'blancée', 'blanc'], answer: 1 },
      { type: 'mcq', question: 'Where do most adjectives go in French?', options: ['Before the noun', 'After the noun', 'At the end', 'Before the verb'], answer: 1 },
      { type: 'mcq', question: 'What is "vieux" in feminine form?', options: ['vieuxe', 'vieille', 'vieusse', 'vieux'], answer: 1 },
      { type: 'mcq', question: 'How do you say "blue eyes"?', options: ['bleus yeux', 'yeux bleus', 'yeux bleues', 'bleu yeux'], answer: 1 },
      { type: 'mcq', question: 'What color is "marron"?', options: ['red', 'purple', 'brown', 'grey'], answer: 2 },
      { type: 'mcq', question: 'What is the plural of "petite"?', options: ['petites', 'petit', 'petits', 'petitees'], answer: 0 },
    ]
  },

  'a1-4': {
    id: 'a1-4', moduleId: 'A1',
    title: { en: 'Family & Relationships', pa: 'ਪਰਿਵਾਰ', es: 'Familia', hi: 'परिवार', ar: 'العائلة' },
    xp: 20,
    vocab: [
      { fr: 'la famille', en: 'family', example: 'J\'adore ma famille.' },
      { fr: 'le père', en: 'father', example: 'Mon père s\'appelle Robert.' },
      { fr: 'la mère', en: 'mother', example: 'Ma mère est médecin.' },
      { fr: 'les parents', en: 'parents', example: 'Mes parents habitent à Québec.' },
      { fr: 'le frère', en: 'brother', example: 'J\'ai un frère aîné.' },
      { fr: 'la sœur', en: 'sister', example: 'Ma sœur est plus jeune que moi.' },
      { fr: 'le fils', en: 'son', example: 'C\'est mon fils, il a 10 ans.' },
      { fr: 'la fille', en: 'daughter', example: 'Ma fille étudie à l\'université.' },
      { fr: 'le mari', en: 'husband', example: 'Mon mari travaille à Ottawa.' },
      { fr: 'la femme', en: 'wife', example: 'Ma femme est enseignante.' },
      { fr: 'le grand-père', en: 'grandfather', example: 'Mon grand-père a 80 ans.' },
      { fr: 'la grand-mère', en: 'grandmother', example: 'Ma grand-mère fait la meilleure cuisine.' },
      { fr: 'l\'oncle', en: 'uncle', example: 'Mon oncle vit en France.' },
      { fr: 'la tante', en: 'aunt', example: 'Ma tante est très gentille.' },
      { fr: 'le cousin / la cousine', en: 'cousin', example: 'J\'ai cinq cousins.' },
      { fr: 'célibataire', en: 'single', example: 'Je suis célibataire pour l\'instant.' },
      { fr: 'marié(e)', en: 'married', example: 'Nous sommes mariés depuis cinq ans.' },
    ],
    grammar: {
      title: 'Possessive Adjectives (mon, ma, mes...)',
      explanation: 'Possessive adjectives show ownership. They agree with the noun not the owner.',
      points: [
        'mon (m.sg) / ma (f.sg) / mes (pl) = my',
        'ton / ta / tes = your (informal)',
        'son / sa / ses = his / her / its',
        'notre / notre / nos = our',
        'votre / votre / vos = your (formal)',
        'leur / leur / leurs = their',
        'Use MON before feminine nouns starting with a vowel: mon amie',
      ],
      examples: [
        'mon père, ma mère, mes parents',
        'ton frère, ta sœur, tes enfants',
        'son mari, sa femme, ses fils',
        'notre famille, nos amis',
        'mon amie Sophie (feminine but starts with vowel)',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you say "my mother"?', options: ['mon mère', 'ma mère', 'mes mère', 'sa mère'], answer: 1 },
      { type: 'mcq', question: 'What is "la sœur"?', options: ['brother', 'sister', 'daughter', 'aunt'], answer: 1 },
      { type: 'mcq', question: 'How do you say "his wife"?', options: ['son femme', 'sa femme', 'ses femme', 'leur femme'], answer: 1 },
      { type: 'mcq', question: '"___ amie" (my friend - feminine)?', options: ['ma', 'mon', 'mes', 'son'], answer: 1 },
      { type: 'mcq', question: 'How do you say "our parents"?', options: ['leur parents', 'nos parents', 'notre parents', 'vos parents'], answer: 1 },
      { type: 'mcq', question: 'What does "marié(e)" mean?', options: ['single', 'divorced', 'married', 'widowed'], answer: 2 },
    ]
  },

  'a1-5': {
    id: 'a1-5', moduleId: 'A1',
    title: { en: 'Days, Months & Seasons', pa: 'ਦਿਨ ਅਤੇ ਮਹੀਨੇ', es: 'Días y meses', hi: 'दिन और महीने', ar: 'الأيام والشهور' },
    xp: 20,
    vocab: [
      { fr: 'lundi', en: 'Monday', example: 'Le cours commence lundi.' },
      { fr: 'mardi', en: 'Tuesday', example: 'Rendez-vous mardi matin.' },
      { fr: 'mercredi', en: 'Wednesday', example: 'Mercredi, je travaille.' },
      { fr: 'jeudi', en: 'Thursday', example: 'Jeudi soir, on sort.' },
      { fr: 'vendredi', en: 'Friday', example: 'C\'est vendredi — le week-end arrive !' },
      { fr: 'samedi', en: 'Saturday', example: 'Samedi, je fais du sport.' },
      { fr: 'dimanche', en: 'Sunday', example: 'Le dimanche, la famille se réunit.' },
      { fr: 'janvier', en: 'January', example: 'Il neige beaucoup en janvier.' },
      { fr: 'février', en: 'February', example: 'La Saint-Valentin est en février.' },
      { fr: 'mars', en: 'March', example: 'Le printemps commence en mars.' },
      { fr: 'avril', en: 'April', example: 'Il pleut souvent en avril.' },
      { fr: 'mai', en: 'May', example: 'Les fleurs poussent en mai.' },
      { fr: 'juin', en: 'June', example: 'L\'école finit en juin.' },
      { fr: 'juillet', en: 'July', example: 'La fête nationale est le 1er juillet.' },
      { fr: 'août', en: 'August', example: 'On part en vacances en août.' },
      { fr: 'septembre', en: 'September', example: 'L\'école reprend en septembre.' },
      { fr: 'octobre', en: 'October', example: 'L\'Halloween est en octobre.' },
      { fr: 'novembre', en: 'November', example: 'Il commence à faire froid en novembre.' },
      { fr: 'décembre', en: 'December', example: 'Noël est le 25 décembre.' },
      { fr: 'le printemps', en: 'spring', example: 'J\'adore le printemps au Québec.' },
      { fr: 'l\'été', en: 'summer', example: 'L\'été canadien est chaud et court.' },
      { fr: 'l\'automne', en: 'autumn/fall', example: 'L\'automne est magnifique avec les feuilles colorées.' },
      { fr: 'l\'hiver', en: 'winter', example: 'L\'hiver au Québec est très rigoureux.' },
    ],
    grammar: {
      title: 'Dates & The Article "Le"',
      explanation: 'In French, days and months are NOT capitalized unlike English.',
      points: [
        'Days and months are masculine and lowercase in French',
        'Le lundi = on Mondays (recurring) | Lundi = this Monday (specific)',
        'For the first of the month: le premier (1er) janvier',
        'Months do NOT use articles: en janvier, en février',
        'Seasons: au printemps, en été, en automne, en hiver',
      ],
      examples: [
        'Aujourd\'hui, c\'est lundi.',
        'Je travaille le vendredi.',
        'Mon anniversaire est le 15 mars.',
        'Nous sommes le premier janvier.',
        'Il fait chaud en été.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'What is Wednesday in French?', options: ['mardi', 'jeudi', 'mercredi', 'vendredi'], answer: 2 },
      { type: 'mcq', question: 'How do you say "in January"?', options: ['le janvier', 'au janvier', 'en janvier', 'à janvier'], answer: 2 },
      { type: 'mcq', question: 'What is "l\'automne"?', options: ['spring', 'summer', 'winter', 'autumn'], answer: 3 },
      { type: 'mcq', question: 'How do you say "on Mondays" (recurring)?', options: ['lundi', 'le lundi', 'un lundi', 'en lundi'], answer: 1 },
      { type: 'mcq', question: 'What is the first month of the year?', options: ['février', 'mars', 'janvier', 'décembre'], answer: 2 },
      { type: 'mcq', question: 'How do you say "in summer"?', options: ['au été', 'en été', 'l\'été', 'dans été'], answer: 1 },
    ]
  },

  'a1-6': {
    id: 'a1-6', moduleId: 'A1',
    title: { en: 'Food, Drinks & Ordering', pa: 'ਖਾਣਾ ਅਤੇ ਪੀਣਾ', es: 'Comida y bebidas', hi: 'खाना और पेय', ar: 'الطعام والشراب' },
    xp: 25,
    vocab: [
      { fr: 'le pain', en: 'bread', example: 'Je voudrais du pain, s\'il vous plaît.' },
      { fr: 'le fromage', en: 'cheese', example: 'Le fromage québécois est délicieux.' },
      { fr: 'la viande', en: 'meat', example: 'Je ne mange pas de viande.' },
      { fr: 'le poisson', en: 'fish', example: 'Je préfère le poisson à la viande.' },
      { fr: 'les légumes', en: 'vegetables', example: 'Mange tes légumes !' },
      { fr: 'les fruits', en: 'fruits', example: 'J\'aime les fruits frais.' },
      { fr: 'le café', en: 'coffee', example: 'Un café, s\'il vous plaît.' },
      { fr: 'le thé', en: 'tea', example: 'Je préfère le thé le matin.' },
      { fr: 'l\'eau', en: 'water', example: 'Une bouteille d\'eau, s\'il vous plaît.' },
      { fr: 'le menu', en: 'menu', example: 'Puis-je voir le menu ?' },
      { fr: 'l\'entrée', en: 'starter', example: 'Comme entrée, je prends la soupe.' },
      { fr: 'le plat principal', en: 'main course', example: 'Et comme plat principal ?' },
      { fr: 'le dessert', en: 'dessert', example: 'Je voudrais un dessert.' },
      { fr: 'l\'addition', en: 'the bill', example: 'L\'addition, s\'il vous plaît !' },
      { fr: 'délicieux/délicieuse', en: 'delicious', example: 'C\'est vraiment délicieux !' },
      { fr: 'J\'ai faim', en: 'I am hungry', example: 'J\'ai très faim, on mange bientôt ?' },
      { fr: 'J\'ai soif', en: 'I am thirsty', example: 'J\'ai soif, je voudrais de l\'eau.' },
    ],
    grammar: {
      title: 'Partitive Articles (du, de la, de l\', des)',
      explanation: 'Partitive articles express an unspecified quantity — like saying some in English.',
      points: [
        'du = de + le (masculine): du pain, du fromage, du café',
        'de la (feminine): de la viande, de la bière',
        'de l\' (before vowel): de l\'eau, de l\'orange',
        'des (plural): des légumes, des fruits',
        'After negation, all become de/d\': Je ne mange pas de viande.',
        'Je voudrais... = I would like... (polite way to order)',
      ],
      examples: [
        'Je mange du pain le matin.',
        'Tu veux de la soupe ?',
        'Il boit de l\'eau.',
        'Nous mangeons des pâtes.',
        'Je ne bois pas de café.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you say "some water"?', options: ['du eau', 'de la eau', 'de l\'eau', 'des eau'], answer: 2 },
      { type: 'mcq', question: 'What is "l\'addition"?', options: ['the menu', 'the dessert', 'the bill', 'the starter'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Je mange ___ pain."', options: ['de la', 'du', 'des', 'de l\''], answer: 1 },
      { type: 'mcq', question: 'How do you say "I am hungry"?', options: ['Je suis faim', 'J\'ai faim', 'Je mange', 'J\'ai mangé'], answer: 1 },
      { type: 'mcq', question: 'After negation, "du/de la/des" become:', options: ['un/une', 'le/la', 'de/d\'', 'pas'], answer: 2 },
      { type: 'mcq', question: 'What does "délicieux" mean?', options: ['expensive', 'delicious', 'fresh', 'spicy'], answer: 1 },
    ]
  },'a2-1': {
    id: 'a2-1', moduleId: 'A2',
    title: { en: 'Present Tense — Regular Verbs', pa: 'ਵਰਤਮਾਨ ਕਾਲ', es: 'Presente', hi: 'वर्तमान काल', ar: 'المضارع' },
    xp: 25,
    vocab: [
      { fr: 'parler', en: 'to speak', example: 'Je parle français tous les jours.' },
      { fr: 'travailler', en: 'to work', example: 'Elle travaille à Montréal.' },
      { fr: 'habiter', en: 'to live', example: 'Nous habitons au Canada.' },
      { fr: 'aimer', en: 'to like/love', example: 'J\'aime apprendre le français.' },
      { fr: 'écouter', en: 'to listen', example: 'Il écoute de la musique.' },
      { fr: 'regarder', en: 'to watch', example: 'Nous regardons la télévision.' },
      { fr: 'manger', en: 'to eat', example: 'Vous mangez à quelle heure ?' },
      { fr: 'voyager', en: 'to travel', example: 'J\'adore voyager au Québec.' },
      { fr: 'finir', en: 'to finish', example: 'Je finis le travail à 17h.' },
      { fr: 'choisir', en: 'to choose', example: 'Tu choisis quoi comme dessert ?' },
      { fr: 'réussir', en: 'to succeed', example: 'Nous réussissons ensemble !' },
      { fr: 'attendre', en: 'to wait', example: 'J\'attends le bus depuis 20 minutes.' },
      { fr: 'répondre', en: 'to answer', example: 'Elle répond au téléphone.' },
      { fr: 'vendre', en: 'to sell', example: 'Il vend des fleurs au marché.' },
      { fr: 'entendre', en: 'to hear', example: 'Vous entendez la musique ?' },
    ],
    grammar: {
      title: 'Three Verb Groups: -ER, -IR, -RE',
      explanation: 'French regular verbs follow three main patterns. Master these and you can conjugate hundreds of verbs.',
      points: [
        '-ER verbs (parler): je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent',
        '-IR verbs (finir): je finis, tu finis, il finit, nous finissons, vous finissez, ils finissent',
        '-RE verbs (attendre): j\'attends, tu attends, il attend, nous attendons, vous attendez, ils attendent',
        '-ER endings: e, es, e, ons, ez, ent',
        '-IR endings: is, is, it, issons, issez, issent',
        '-RE endings: s, s, (nothing), ons, ez, ent',
      ],
      examples: [
        'Je parle français. (I speak French.)',
        'Tu travailles beaucoup. (You work a lot.)',
        'Nous finissons à 18h. (We finish at 6pm.)',
        'Ils attendent le train. (They are waiting for the train.)',
        'Vous répondez vite. (You answer quickly.)',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Conjugate "parler" for "nous":', options: ['parlons', 'parlent', 'parlez', 'parlions'], answer: 0 },
      { type: 'mcq', question: 'Conjugate "finir" for "ils":', options: ['finissons', 'finissent', 'finisent', 'finissez'], answer: 1 },
      { type: 'mcq', question: 'Conjugate "attendre" for "il":', options: ['attends', 'attend', 'attendit', 'attendons'], answer: 1 },
      { type: 'mcq', question: 'What type of verb is "manger"?', options: ['-IR verb', '-RE verb', '-ER verb', 'irregular'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Vous ___ à quelle heure ?" (travailler)', options: ['travaillez', 'travaillons', 'travaillent', 'travailler'], answer: 0 },
      { type: 'mcq', question: 'Conjugate "choisir" for "je":', options: ['choisis', 'choisit', 'choisissons', 'choisisse'], answer: 0 },
      { type: 'mcq', question: 'Complete: "Elle ___ au téléphone." (répondre)', options: ['répond', 'répondit', 'réponds', 'répondons'], answer: 0 },
      { type: 'mcq', question: 'What does "réussir" mean?', options: ['to try', 'to fail', 'to succeed', 'to start'], answer: 2 },
    ]
  },

  'a2-2': {
    id: 'a2-2', moduleId: 'A2',
    title: { en: 'Telling the Time', pa: 'ਸਮਾਂ ਦੱਸਣਾ', es: 'Decir la hora', hi: 'समय बताना', ar: 'قول الوقت' },
    xp: 25,
    vocab: [
      { fr: 'Quelle heure est-il ?', en: 'What time is it?', example: 'Excusez-moi, quelle heure est-il ?' },
      { fr: 'Il est... heure(s)', en: 'It is... o\'clock', example: 'Il est trois heures.' },
      { fr: 'et quart', en: 'quarter past', example: 'Il est deux heures et quart.' },
      { fr: 'et demie', en: 'half past', example: 'Il est six heures et demie.' },
      { fr: 'moins le quart', en: 'quarter to', example: 'Il est quatre heures moins le quart.' },
      { fr: 'du matin', en: 'in the morning (am)', example: 'Il est huit heures du matin.' },
      { fr: 'de l\'après-midi', en: 'in the afternoon (pm)', example: 'Il est trois heures de l\'après-midi.' },
      { fr: 'du soir', en: 'in the evening', example: 'Il est neuf heures du soir.' },
      { fr: 'midi', en: 'noon', example: 'On se retrouve à midi ?' },
      { fr: 'minuit', en: 'midnight', example: 'Le film finit à minuit.' },
      { fr: 'tôt', en: 'early', example: 'Je me lève tôt le matin.' },
      { fr: 'tard', en: 'late', example: 'Il rentre toujours tard.' },
      { fr: 'maintenant', en: 'now', example: 'Je suis occupé maintenant.' },
      { fr: 'bientôt', en: 'soon', example: 'On arrive bientôt !' },
      { fr: 'tout de suite', en: 'right away', example: 'J\'arrive tout de suite !' },
    ],
    grammar: {
      title: 'Telling Time — 12h & 24h Systems',
      explanation: 'French has two systems for telling time. The 24-hour system is used for schedules and transport.',
      points: [
        '12-hour: Il est deux heures et demie. (2:30)',
        '24-hour: Il est quatorze heures trente. (14:30)',
        'Minutes past: Il est cinq heures vingt (5:20)',
        'Minutes to: Il est six heures moins dix (5:50)',
        'Special: midi (12:00), minuit (0:00), midi et demi (12:30)',
        'Transport always uses 24-hour time in French',
      ],
      examples: [
        '8:00 = Il est huit heures.',
        '8:15 = Il est huit heures et quart.',
        '8:30 = Il est huit heures et demie.',
        '8:45 = Il est neuf heures moins le quart.',
        '20:30 (official) = Il est vingt heures trente.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you say 3:30?', options: ['Il est trois heures moins demie', 'Il est trois heures et demie', 'Il est deux heures et demie', 'Il est trois heures trente'], answer: 1 },
      { type: 'mcq', question: 'What does "midi" mean?', options: ['midnight', 'morning', 'noon', 'evening'], answer: 2 },
      { type: 'mcq', question: 'How do you say 4:45?', options: ['Il est cinq heures moins le quart', 'Il est quatre heures et quart', 'Il est cinq heures le quart', 'Il est quatre heures quarante'], answer: 0 },
      { type: 'mcq', question: 'In 24-hour time, 14:00 is:', options: ['deux heures', 'quatorze heures', 'quatre heures', 'midi'], answer: 1 },
      { type: 'mcq', question: 'What does "tôt" mean?', options: ['late', 'soon', 'early', 'now'], answer: 2 },
    ]
  },

  'a2-3': {
    id: 'a2-3', moduleId: 'A2',
    title: { en: 'Daily Routines & Reflexive Verbs', pa: 'ਰੋਜ਼ਾਨਾ ਰੁਟੀਨ', es: 'Rutina diaria', hi: 'दैनिक दिनचर्या', ar: 'الروتين اليومي' },
    xp: 30,
    vocab: [
      { fr: 'se lever', en: 'to get up', example: 'Je me lève à sept heures.' },
      { fr: 'se réveiller', en: 'to wake up', example: 'Tu te réveilles à quelle heure ?' },
      { fr: 'se doucher', en: 'to shower', example: 'Il se douche chaque matin.' },
      { fr: 'se brosser les dents', en: 'to brush teeth', example: 'Je me brosse les dents après le repas.' },
      { fr: 's\'habiller', en: 'to get dressed', example: 'Les enfants s\'habillent seuls.' },
      { fr: 'se dépêcher', en: 'to hurry', example: 'Dépêche-toi, on est en retard !' },
      { fr: 'se coucher', en: 'to go to bed', example: 'Je me couche à 23h en semaine.' },
      { fr: 's\'endormir', en: 'to fall asleep', example: 'Je m\'endors toujours devant la télé.' },
      { fr: 'petit-déjeuner', en: 'breakfast', example: 'Je prends le petit-déjeuner à 8h.' },
      { fr: 'déjeuner', en: 'lunch', example: 'On déjeune ensemble ?' },
      { fr: 'dîner', en: 'dinner', example: 'La famille dîne à 19h.' },
      { fr: 'aller au travail', en: 'to go to work', example: 'Je vais au travail en métro.' },
      { fr: 'rentrer à la maison', en: 'to come home', example: 'Je rentre à la maison vers 18h.' },
    ],
    grammar: {
      title: 'Reflexive Verbs (Verbes pronominaux)',
      explanation: 'Reflexive verbs describe actions done to oneself. They use reflexive pronouns before the verb.',
      points: [
        'je me lève, tu te lèves, il/elle se lève',
        'nous nous levons, vous vous levez, ils/elles se lèvent',
        'In questions: Tu te lèves tôt ?',
        'In negation: Je ne me lève pas tard.',
        'Many daily routine verbs are reflexive in French',
      ],
      examples: [
        'Je me réveille à 7h.',
        'Elle se douche le soir.',
        'Nous nous couchons à 22h.',
        'Vous vous habillez rapidement.',
        'Ils se dépêchent ce matin.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Complete: "Je ___ à 7h." (se lever)', options: ['me lève', 'se lève', 'te lèves', 'nous levons'], answer: 0 },
      { type: 'mcq', question: 'What does "se coucher" mean?', options: ['to shower', 'to wake up', 'to go to bed', 'to get dressed'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Ils ___ vite." (se dépêcher)', options: ['me dépêchent', 'se dépêchent', 'te dépêches', 'vous dépêchez'], answer: 1 },
      { type: 'mcq', question: 'What is "petit-déjeuner"?', options: ['lunch', 'dinner', 'snack', 'breakfast'], answer: 3 },
      { type: 'mcq', question: 'Negative of "Je me lève tôt":', options: ['Je ne se lève pas tôt', 'Je me lève pas tôt', 'Je ne me lève pas tôt', 'Je ne me lèves pas tôt'], answer: 2 },
    ]
  },

  'a2-4': {
    id: 'a2-4', moduleId: 'A2',
    title: { en: 'Transportation & Getting Around', pa: 'ਆਵਾਜਾਈ', es: 'Transporte', hi: 'परिवहन', ar: 'المواصلات' },
    xp: 25,
    vocab: [
      { fr: 'le métro', en: 'subway', example: 'Je prends le métro pour aller au travail.' },
      { fr: 'le bus', en: 'bus', example: 'Le bus 24 passe toutes les 10 minutes.' },
      { fr: 'le train', en: 'train', example: 'Le train pour Ottawa part à 9h.' },
      { fr: 'l\'avion', en: 'airplane', example: 'Le vol dure cinq heures.' },
      { fr: 'la voiture', en: 'car', example: 'Je viens en voiture.' },
      { fr: 'à pied', en: 'on foot', example: 'J\'y vais à pied, c\'est près.' },
      { fr: 'le billet', en: 'ticket', example: 'Deux billets aller-retour, s\'il vous plaît.' },
      { fr: 'aller simple', en: 'one-way ticket', example: 'Un aller simple pour Québec.' },
      { fr: 'aller-retour', en: 'return ticket', example: 'Un aller-retour Montréal-Toronto.' },
      { fr: 'la gare', en: 'train station', example: 'La gare Centrale est dans le centre-ville.' },
      { fr: 'l\'aéroport', en: 'airport', example: 'L\'aéroport est loin du centre.' },
      { fr: 'Où est... ?', en: 'Where is...?', example: 'Excusez-moi, où est la station de métro ?' },
      { fr: 'tournez à gauche', en: 'turn left', example: 'Tournez à gauche au feu rouge.' },
      { fr: 'tournez à droite', en: 'turn right', example: 'Tournez à droite après le pont.' },
      { fr: 'tout droit', en: 'straight ahead', example: 'Continuez tout droit pendant 500 mètres.' },
    ],
    grammar: {
      title: 'Prepositions of Place & Direction',
      explanation: 'Knowing how to give and understand directions is essential for daily life in a French-speaking city.',
      points: [
        'à = to/at/in (cities): Je vais à Montréal.',
        'en = in (countries/transport): Je vis en France. Je voyage en train.',
        'près de = near: La gare est près d\'ici.',
        'loin de = far from: L\'aéroport est loin du centre.',
        'en face de = opposite: C\'est en face de l\'hôtel.',
        'au coin de = at the corner of: C\'est au coin de la rue.',
      ],
      examples: [
        'Prenez la rue principale.',
        'Tournez à droite au carrefour.',
        'C\'est à cinq minutes à pied.',
        'La station est en face de l\'hôtel.',
        'Descendez à la prochaine station.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'What is "aller-retour"?', options: ['one-way', 'return ticket', 'monthly pass', 'group ticket'], answer: 1 },
      { type: 'mcq', question: 'How do you say "straight ahead"?', options: ['tournez à droite', 'tout droit', 'à gauche', 'en face'], answer: 1 },
      { type: 'mcq', question: 'Complete: "Je voyage ___ train."', options: ['à', 'au', 'en', 'par'], answer: 2 },
      { type: 'mcq', question: 'What is "la gare"?', options: ['airport', 'bus stop', 'train station', 'subway'], answer: 2 },
      { type: 'mcq', question: 'How do you ask "Where is the metro?"', options: ['Comment est le métro ?', 'Où est la station de métro ?', 'Quand est le métro ?', 'Combien est le métro ?'], answer: 1 },
    ]
  },

  'a2-5': {
    id: 'a2-5', moduleId: 'A2',
    title: { en: 'Shopping & Money', pa: 'ਖਰੀਦਦਾਰੀ', es: 'Compras', hi: 'खरीदारी', ar: 'التسوق' },
    xp: 25,
    vocab: [
      { fr: 'combien ça coûte ?', en: 'how much does it cost?', example: 'Combien ça coûte, ce manteau ?' },
      { fr: 'c\'est cher', en: 'it\'s expensive', example: 'Cent dollars ? C\'est cher !' },
      { fr: 'c\'est bon marché', en: 'it\'s cheap', example: 'C\'est bon marché pour la qualité.' },
      { fr: 'la taille', en: 'size (clothing)', example: 'Quelle taille faites-vous ?' },
      { fr: 'le prix', en: 'price', example: 'Quel est le prix de cet article ?' },
      { fr: 'la caisse', en: 'checkout', example: 'Payez à la caisse, s\'il vous plaît.' },
      { fr: 'la carte de crédit', en: 'credit card', example: 'Vous acceptez la carte de crédit ?' },
      { fr: 'les soldes', en: 'sales', example: 'Il y a des soldes ce week-end !' },
      { fr: 'une réduction', en: 'a discount', example: 'Avez-vous une réduction pour étudiants ?' },
      { fr: 'le reçu', en: 'receipt', example: 'Puis-je avoir un reçu ?' },
      { fr: 'essayer', en: 'to try on', example: 'Puis-je essayer cette veste ?' },
    ],
    grammar: {
      title: 'Three Ways to Ask Questions',
      explanation: 'In French there are three main ways to ask questions. All three appear in TEF.',
      points: [
        'Intonation (informal): Vous avez ce en taille M ? (rising voice)',
        'Est-ce que (standard): Est-ce que vous avez ce en taille M ?',
        'Inversion (formal): Avez-vous ce en taille M ?',
        'Question words: Combien, Quel/Quelle, Où, Quand, Comment, Pourquoi',
        'For prices: Combien coûte... ? / Quel est le prix de... ?',
      ],
      examples: [
        'Combien coûte cette robe ?',
        'Est-ce que vous acceptez Visa ?',
        'Avez-vous une plus grande taille ?',
        'Où est la cabine d\'essayage ?',
        'Quel est le prix de ce manteau ?',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you ask "how much does it cost"?', options: ['Quel prix ?', 'Combien ça coûte ?', 'Comment le prix ?', 'Où est le prix ?'], answer: 1 },
      { type: 'mcq', question: 'What does "les soldes" mean?', options: ['prices', 'sales', 'receipts', 'sizes'], answer: 1 },
      { type: 'mcq', question: 'Which is the most formal question form?', options: ['intonation', 'est-ce que', 'inversion', 'none'], answer: 2 },
      { type: 'mcq', question: 'What is "la caisse"?', options: ['fitting room', 'checkout', 'price tag', 'bag'], answer: 1 },
      { type: 'mcq', question: 'How do you say "Can I try this on?"', options: ['Je peux acheter ça ?', 'Puis-je essayer ça ?', 'Je voudrais ça ?', 'C\'est combien ça ?'], answer: 1 },
    ]
  },

  'b1-1': {
    id: 'b1-1', moduleId: 'B1',
    title: { en: 'Passé Composé — Past Tense', pa: 'ਭੂਤ ਕਾਲ', es: 'Pasado compuesto', hi: 'भूत काल', ar: 'الماضي المركب' },
    xp: 35,
    vocab: [
      { fr: 'j\'ai mangé', en: 'I ate', example: 'J\'ai mangé une poutine hier soir.' },
      { fr: 'j\'ai travaillé', en: 'I worked', example: 'J\'ai travaillé toute la journée.' },
      { fr: 'j\'ai fini', en: 'I finished', example: 'J\'ai fini le rapport à temps.' },
      { fr: 'j\'ai pris', en: 'I took', example: 'J\'ai pris le métro ce matin.' },
      { fr: 'je suis allé(e)', en: 'I went', example: 'Je suis allé au supermarché.' },
      { fr: 'je suis arrivé(e)', en: 'I arrived', example: 'Je suis arrivée à 9h00 précises.' },
      { fr: 'je suis parti(e)', en: 'I left', example: 'Il est parti tôt ce matin.' },
      { fr: 'j\'ai vu', en: 'I saw', example: 'J\'ai vu un excellent film hier.' },
      { fr: 'j\'ai dit', en: 'I said', example: 'J\'ai dit la vérité.' },
      { fr: 'j\'ai fait', en: 'I did/made', example: 'J\'ai fait du sport ce matin.' },
      { fr: 'j\'ai eu', en: 'I had', example: 'J\'ai eu un entretien d\'embauche.' },
      { fr: 'j\'ai été', en: 'I was/been', example: 'J\'ai été malade la semaine dernière.' },
      { fr: 'hier', en: 'yesterday', example: 'Hier, j\'ai visité le Vieux-Montréal.' },
      { fr: 'la semaine dernière', en: 'last week', example: 'La semaine dernière, on a eu beaucoup de neige.' },
    ],
    grammar: {
      title: 'Passé Composé: avoir/être + Past Participle',
      explanation: 'The passé composé is the most common past tense in spoken French.',
      points: [
        'Most verbs use AVOIR: j\'ai mangé, tu as fini, il a pris',
        '17 verbs use ÊTRE: aller, venir, arriver, partir, naître, mourir, rester, monter, descendre, entrer, sortir, tomber, retourner, passer, devenir, revenir, rentrer',
        'ALL reflexive verbs use ÊTRE: je me suis levé(e)',
        'With ÊTRE, past participle agrees with subject gender/number',
        'Past participle patterns: -er→é, -ir→i, -re→u',
        'Irregular: faire→fait, voir→vu, prendre→pris, dire→dit, avoir→eu, être→été',
      ],
      examples: [
        'J\'ai mangé une pomme.',
        'Elle est allée au marché. (feminine agreement)',
        'Ils sont partis tôt. (masculine plural)',
        'Nous nous sommes levés à 7h. (reflexive)',
        'J\'ai vu Marie.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Which auxiliary does "aller" use in passé composé?', options: ['avoir', 'être', 'either', 'neither'], answer: 1 },
      { type: 'mcq', question: 'Complete: "Elle ___ au cinéma." (aller)', options: ['a allée', 'est allée', 'est allé', 'a allé'], answer: 1 },
      { type: 'mcq', question: 'Past participle of "faire":', options: ['faitu', 'faisé', 'fait', 'faité'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Nous ___ à 8h." (arriver)', options: ['avons arrivés', 'sommes arrivés', 'sommes arrivé', 'avons arrivé'], answer: 1 },
      { type: 'mcq', question: 'What does "j\'ai eu" mean?', options: ['I went', 'I was born', 'I had', 'I said'], answer: 2 },
      { type: 'mcq', question: 'Past participle of "prendre":', options: ['prendu', 'prené', 'pris', 'prend'], answer: 2 },
      { type: 'mcq', question: 'Reflexive verbs use which auxiliary?', options: ['avoir', 'être', 'aller', 'faire'], answer: 1 },
      { type: 'mcq', question: 'Complete: "Ils ___ le bus." (prendre)', options: ['sont pris', 'ont pris', 'ont prenu', 'sont prenu'], answer: 1 },
    ]
  },

  'b1-2': {
    id: 'b1-2', moduleId: 'B1',
    title: { en: 'Expressing Opinions & Emotions', pa: 'ਵਿਚਾਰ ਅਤੇ ਭਾਵਨਾਵਾਂ', es: 'Opiniones y emociones', hi: 'राय और भावनाएँ', ar: 'الآراء والمشاعر' },
    xp: 30,
    vocab: [
      { fr: 'Je pense que', en: 'I think that', example: 'Je pense que c\'est une bonne idée.' },
      { fr: 'Je crois que', en: 'I believe that', example: 'Je crois que nous avons raison.' },
      { fr: 'À mon avis', en: 'In my opinion', example: 'À mon avis, c\'est trop cher.' },
      { fr: 'Selon moi', en: 'According to me', example: 'Selon moi, l\'éducation est essentielle.' },
      { fr: 'Je suis d\'accord', en: 'I agree', example: 'Je suis tout à fait d\'accord avec vous.' },
      { fr: 'Je ne suis pas d\'accord', en: 'I disagree', example: 'Désolé, je ne suis pas d\'accord.' },
      { fr: 'Cependant', en: 'However', example: 'C\'est cher, cependant la qualité est excellente.' },
      { fr: 'En revanche', en: 'On the other hand', example: 'En revanche, les avantages sont nombreux.' },
      { fr: 'D\'une part... d\'autre part', en: 'On one hand... on the other', example: 'D\'une part pratique, d\'autre part coûteux.' },
      { fr: 'être content(e)', en: 'to be happy', example: 'Je suis très content de mon résultat.' },
      { fr: 'être triste', en: 'to be sad', example: 'Elle est triste de partir.' },
      { fr: 'être inquiet/inquiète', en: 'to be worried', example: 'Je suis inquiet pour les examens.' },
      { fr: 'être fier/fière', en: 'to be proud', example: 'Je suis fier de mes progrès en français.' },
    ],
    grammar: {
      title: 'Subjunctive After Opinion Expressions',
      explanation: 'The subjunctive mood is used after certain expressions of opinion, doubt, emotion, and desire.',
      points: [
        'Use subjunctive after: je veux que, il faut que, je suis content que, je doute que',
        'Use indicative after: je pense que, je crois que (expressing certainty)',
        'Key subjunctive triggers: vouloir que, falloir que, être content/triste que',
        'When both verbs have same subject, use infinitive: Je veux partir',
      ],
      examples: [
        'Je pense qu\'il a raison. (indicative)',
        'Je veux qu\'il vienne. (subjunctive)',
        'Il faut que vous parliez français. (subjunctive)',
        'Je suis content que tu sois là. (subjunctive)',
        'Je doute qu\'il finisse à temps. (subjunctive)',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Which is followed by subjunctive?', options: ['Je pense que', 'Je crois que', 'Il faut que', 'Il est clair que'], answer: 2 },
      { type: 'mcq', question: 'What does "À mon avis" mean?', options: ['In my opinion', 'According to others', 'I believe', 'I agree'], answer: 0 },
      { type: 'mcq', question: '"Cependant" means:', options: ['therefore', 'however', 'moreover', 'because'], answer: 1 },
      { type: 'mcq', question: 'Complete: "Je suis content ___ tu sois là."', options: ['que', 'de', 'qui', 'pour'], answer: 0 },
      { type: 'mcq', question: 'How do you say "I disagree"?', options: ['Je suis d\'accord', 'Je ne suis pas d\'accord', 'Je pense pas', 'Pas vrai'], answer: 1 },
      { type: 'mcq', question: '"D\'une part... d\'autre part" expresses:', options: ['time', 'two sides/contrast', 'cause and effect', 'addition'], answer: 1 },
    ]
  },

  'b1-3': {
    id: 'b1-3', moduleId: 'B1',
    title: { en: 'Work, Career & Professional French', pa: 'ਕੰਮ ਅਤੇ ਕੈਰੀਅਰ', es: 'Trabajo y carrera', hi: 'काम और कैरियर', ar: 'العمل والمهنة' },
    xp: 35,
    vocab: [
      { fr: 'le poste', en: 'job position', example: 'Je candidate pour le poste d\'ingénieur.' },
      { fr: 'l\'entretien d\'embauche', en: 'job interview', example: 'J\'ai un entretien d\'embauche demain.' },
      { fr: 'le curriculum vitae (CV)', en: 'resume/CV', example: 'Mon CV est à jour.' },
      { fr: 'le salaire', en: 'salary', example: 'Quel est le salaire proposé ?' },
      { fr: 'les compétences', en: 'skills', example: 'J\'ai des compétences en informatique.' },
      { fr: 'le contrat', en: 'contract', example: 'J\'ai signé un contrat de deux ans.' },
      { fr: 'à temps plein', en: 'full-time', example: 'Je cherche un emploi à temps plein.' },
      { fr: 'à temps partiel', en: 'part-time', example: 'Je travaille à temps partiel.' },
      { fr: 'les congés', en: 'leave / vacation days', example: 'J\'ai deux semaines de congés payés.' },
      { fr: 'la réunion', en: 'meeting', example: 'La réunion commence à 9h.' },
      { fr: 'le collègue', en: 'colleague', example: 'Mes collègues sont très sympathiques.' },
      { fr: 'le patron / la patronne', en: 'boss', example: 'Mon patron est exigeant mais juste.' },
      { fr: 'démissionner', en: 'to resign', example: 'Elle a démissionné pour créer sa propre entreprise.' },
      { fr: 'une augmentation', en: 'a raise', example: 'Je vais demander une augmentation.' },
    ],
    grammar: {
      title: 'Conditional Tense for Polite Requests',
      explanation: 'The conditional tense is essential in professional contexts for polite requests and hypotheticals.',
      points: [
        'Formation: infinitive + imperfect endings (-ais, -ais, -ait, -ions, -iez, -aient)',
        'Je voudrais = I would like (polite) vs Je veux = I want (direct)',
        'Pourriez-vous... ? = Could you...? (very polite)',
        'Si + imparfait + conditionnel: Si j\'avais le temps, j\'étudierais plus.',
        'Key conditional verbs: voudrais, pourrait, devrait, faudrait, serait',
      ],
      examples: [
        'Je voudrais postuler pour ce poste.',
        'Pourriez-vous m\'envoyer le contrat ?',
        'Il devrait arriver à 9h.',
        'Si j\'avais plus d\'expérience, j\'aurais ce poste.',
        'Ce serait une bonne opportunité.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Polite way to say "I want a coffee":', options: ['Je veux un café', 'Je voudrais un café', 'Donne-moi un café', 'J\'aime un café'], answer: 1 },
      { type: 'mcq', question: 'What is "l\'entretien d\'embauche"?', options: ['contract', 'salary', 'job interview', 'resume'], answer: 2 },
      { type: 'mcq', question: 'Conditional of "pouvoir" for vous:', options: ['pouvez', 'pouviez', 'pourriez', 'pourrez'], answer: 2 },
      { type: 'mcq', question: 'What does "à temps partiel" mean?', options: ['full-time', 'part-time', 'overtime', 'freelance'], answer: 1 },
      { type: 'mcq', question: '"Si j\'avais le temps, j\'___" (étudier):', options: ['étudie', 'étudierais', 'étudiais', 'étudierai'], answer: 1 },
      { type: 'mcq', question: 'What is "une augmentation"?', options: ['a promotion', 'a raise', 'a bonus', 'a contract'], answer: 1 },
    ]
  },

  'b1-4': {
    id: 'b1-4', moduleId: 'B1',
    title: { en: 'Health, Body & Medical French', pa: 'ਸਿਹਤ ਅਤੇ ਸਰੀਰ', es: 'Salud y cuerpo', hi: 'स्वास्थ्य और शरीर', ar: 'الصحة والجسم' },
    xp: 30,
    vocab: [
      { fr: 'avoir mal à', en: 'to have pain in', example: 'J\'ai mal à la tête depuis ce matin.' },
      { fr: 'la tête', en: 'head', example: 'J\'ai mal à la tête.' },
      { fr: 'le dos', en: 'back', example: 'Je souffre du dos depuis des années.' },
      { fr: 'la gorge', en: 'throat', example: 'J\'ai mal à la gorge.' },
      { fr: 'l\'estomac', en: 'stomach', example: 'J\'ai mal à l\'estomac.' },
      { fr: 'la fièvre', en: 'fever', example: 'Il a 39 de fièvre.' },
      { fr: 'la toux', en: 'cough', example: 'Cette toux dure depuis une semaine.' },
      { fr: 'être enrhumé(e)', en: 'to have a cold', example: 'Je suis enrhumée.' },
      { fr: 'l\'ordonnance', en: 'prescription', example: 'Le médecin m\'a donné une ordonnance.' },
      { fr: 'la pharmacie', en: 'pharmacy', example: 'Il y a une pharmacie au coin.' },
      { fr: 'les médicaments', en: 'medication', example: 'Prenez ces médicaments trois fois par jour.' },
      { fr: 'se sentir bien/mal', en: 'to feel well/unwell', example: 'Je ne me sens pas bien aujourd\'hui.' },
      { fr: 'prendre rendez-vous', en: 'to make an appointment', example: 'J\'ai pris rendez-vous chez le médecin.' },
      { fr: 'la carte d\'assurance maladie', en: 'health insurance card', example: 'N\'oubliez pas votre carte d\'assurance maladie.' },
    ],
    grammar: {
      title: 'Avoir for Physical Sensations',
      explanation: 'Unlike English where we say "I am sick/cold/hungry," French uses AVOIR for many physical sensations.',
      points: [
        'avoir mal à + body part = to have pain in',
        'avoir chaud/froid = to be hot/cold',
        'avoir faim/soif = to be hungry/thirsty',
        'avoir de la fièvre = to have a fever',
        'avoir l\'air + adjective = to look/seem',
        'se sentir + adjective = to feel (reflexive)',
      ],
      examples: [
        'J\'ai mal aux dents. (I have a toothache.)',
        'Elle a de la fièvre.',
        'Tu as l\'air fatigué.',
        'Je me sens mieux aujourd\'hui.',
        'Il a froid — ferme la fenêtre !',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How do you say "I have a headache"?', options: ['Je suis mal à la tête', 'J\'ai mal à la tête', 'Ma tête fait mal', 'J\'ai la tête malade'], answer: 1 },
      { type: 'mcq', question: 'What is "une ordonnance"?', options: ['appointment', 'pharmacy', 'prescription', 'waiting room'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Je ___ bien." (se sentir)', options: ['sens', 'me sens', 'suis senti', 'ai senti'], answer: 1 },
      { type: 'mcq', question: '"To have a fever" in French:', options: ['être fiévreux', 'avoir de la fièvre', 'avoir chaud', 'se sentir chaud'], answer: 1 },
      { type: 'mcq', question: 'What is "la carte d\'assurance maladie"?', options: ['doctor\'s note', 'prescription', 'health insurance card', 'hospital bill'], answer: 2 },
    ]
  },

  'b1-5': {
    id: 'b1-5', moduleId: 'B1',
    title: { en: 'Immigration & Life in Canada', pa: 'ਇਮੀਗ੍ਰੇਸ਼ਨ ਅਤੇ ਕੈਨੇਡਾ', es: 'Inmigración y vida en Canadá', hi: 'आप्रवासन और कनाडा', ar: 'الهجرة والحياة في كندا' },
    xp: 35,
    vocab: [
      { fr: 'le permis de travail', en: 'work permit', example: 'J\'ai obtenu mon permis de travail.' },
      { fr: 'la résidence permanente', en: 'permanent residence', example: 'Ma demande de résidence permanente est en cours.' },
      { fr: 'la citoyenneté', en: 'citizenship', example: 'Je veux obtenir la citoyenneté canadienne.' },
      { fr: 'le passeport', en: 'passport', example: 'Mon passeport expire l\'année prochaine.' },
      { fr: 'le formulaire', en: 'form', example: 'Il faut remplir ce formulaire en français.' },
      { fr: 'le numéro d\'assurance sociale', en: 'social insurance number (SIN)', example: 'J\'ai besoin de mon numéro d\'assurance sociale.' },
      { fr: 's\'intégrer', en: 'to integrate', example: 'Je veux m\'intégrer dans la société québécoise.' },
      { fr: 'les droits', en: 'rights', example: 'Vous avez le droit de travailler au Canada.' },
      { fr: 'bilingue', en: 'bilingual', example: 'Le Canada est officiellement bilingue.' },
      { fr: 'les deux langues officielles', en: 'the two official languages', example: 'Le français et l\'anglais sont les deux langues officielles.' },
      { fr: 'le CLB', en: 'Canadian Language Benchmark', example: 'Le CLB 7 est requis pour plusieurs programmes.' },
      { fr: 'le TEF Canada', en: 'TEF Canada exam', example: 'J\'ai réussi le TEF Canada.' },
    ],
    grammar: {
      title: 'Future Tense (Futur Simple)',
      explanation: 'The simple future tense is used for future plans, predictions, and promises.',
      points: [
        'Formation: infinitive + endings: -ai, -as, -a, -ons, -ez, -ont',
        'je parlerai, tu parleras, il parlera, nous parlerons, vous parlerez, ils parleront',
        'Irregular stems: être→ser, avoir→aur, aller→ir, faire→fer, pouvoir→pourr',
        'After "quand" in French, use future (not present like English)',
      ],
      examples: [
        'Je passerai le TEF le mois prochain.',
        'Quand j\'aurai ma résidence permanente, je travaillerai dans mon domaine.',
        'Nous serons citoyens dans cinq ans.',
        'Elle pourra voter aux prochaines élections.',
        'Ils feront leur demande l\'année prochaine.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Future tense of "parler" for "je":', options: ['parlerai', 'parlerait', 'parlera', 'parlais'], answer: 0 },
      { type: 'mcq', question: 'What is "la résidence permanente"?', options: ['citizenship', 'work permit', 'permanent residence', 'passport'], answer: 2 },
      { type: 'mcq', question: 'Irregular future stem of "être":', options: ['êtr-', 'ét-', 'ser-', 'est-'], answer: 2 },
      { type: 'mcq', question: 'What is the SIN (numéro d\'assurance sociale)?', options: ['passport number', 'social insurance number', 'health card', 'tax number'], answer: 1 },
      { type: 'mcq', question: 'Complete: "Quand j\'aurai mon permis, je ___." (travailler)', options: ['travaille', 'travaillais', 'travaillerai', 'ai travaillé'], answer: 2 },
      { type: 'mcq', question: 'What does "bilingue" mean?', options: ['monolingual', 'trilingual', 'bilingual', 'multilingual'], answer: 2 },
    ]
  },'b2-1': {
    id: 'b2-1', moduleId: 'B2',
    title: { en: 'Complex Grammar — Subjunctive & Nuance', pa: 'ਗੁੰਝਲਦਾਰ ਵਿਆਕਰਨ', es: 'Gramática avanzada', hi: 'उन्नत व्याकरण', ar: 'القواعد المتقدمة' },
    xp: 40,
    vocab: [
      { fr: 'bien que + subjonctif', en: 'although', example: 'Bien qu\'il soit tard, je continue à étudier.' },
      { fr: 'pour que + subjonctif', en: 'so that', example: 'Je parle lentement pour que tu comprennes.' },
      { fr: 'avant que + subjonctif', en: 'before (that)', example: 'Dis-le-lui avant qu\'il parte.' },
      { fr: 'à moins que + subjonctif', en: 'unless', example: 'Je viendrai à moins qu\'il pleuve.' },
      { fr: 'il est possible que', en: 'it is possible that', example: 'Il est possible qu\'il soit en retard.' },
      { fr: 'il est nécessaire que', en: 'it is necessary that', example: 'Il est nécessaire que vous parliez français.' },
      { fr: 'douter que', en: 'to doubt that', example: 'Je doute qu\'il réussisse sans effort.' },
      { fr: 'souhaiter que', en: 'to wish that', example: 'Je souhaite que vous réussissiez.' },
      { fr: 'néanmoins', en: 'nevertheless', example: 'C\'est difficile, néanmoins c\'est possible.' },
      { fr: 'en outre', en: 'furthermore', example: 'En outre, les résultats sont encourageants.' },
      { fr: 'par conséquent', en: 'consequently', example: 'Il a travaillé dur. Par conséquent, il a réussi.' },
      { fr: 'compte tenu de', en: 'given / considering', example: 'Compte tenu de la situation, c\'est normal.' },
    ],
    grammar: {
      title: 'Advanced Subjunctive & Discourse Connectors',
      explanation: 'At B2 level, master all subjunctive triggers and use sophisticated connectors — essential for TEF writing.',
      points: [
        'Subjunctive after: bien que, quoique, pour que, avant que, à moins que',
        'Subjunctive after: vouloir que, craindre que, douter que, souhaiter que',
        'Subjunctive after impersonal: il faut que, il est possible que, il est nécessaire que',
        'Opposition: néanmoins, cependant, toutefois, en revanche',
        'Addition: de plus, en outre, par ailleurs',
        'Consequence: donc, ainsi, par conséquent, c\'est pourquoi',
      ],
      examples: [
        'Bien qu\'il soit difficile, le TEF est surmontable.',
        'Je parle lentement pour que tu comprennes tout.',
        'Il viendra à moins qu\'il ne soit malade.',
        'Les résultats sont bons. Par conséquent, nous sommes optimistes.',
        'En outre, le programme offre de nombreux avantages.',
      ]
    },
    exercises: [
      { type: 'mcq', question: '"Bien que" is followed by:', options: ['indicative', 'infinitive', 'subjunctive', 'conditional'], answer: 2 },
      { type: 'mcq', question: 'What does "néanmoins" mean?', options: ['therefore', 'furthermore', 'nevertheless', 'although'], answer: 2 },
      { type: 'mcq', question: '"Par conséquent" introduces:', options: ['a cause', 'a consequence', 'a contrast', 'an example'], answer: 1 },
      { type: 'mcq', question: 'Complete: "Je parle lentement pour ___ tu comprennes."', options: ['que', 'quoi', 'dont', 'où'], answer: 0 },
      { type: 'mcq', question: '"En outre" means:', options: ['however', 'therefore', 'furthermore', 'unless'], answer: 2 },
      { type: 'mcq', question: 'Which requires subjunctive?', options: ['Je pense que', 'Il est clair que', 'Il est possible que', 'Je suis sûr que'], answer: 2 },
    ]
  },

  'b2-2': {
    id: 'b2-2', moduleId: 'B2',
    title: { en: 'Society & Current Events', pa: 'ਸਮਾਜ ਅਤੇ ਮੌਜੂਦਾ ਘਟਨਾਵਾਂ', es: 'Sociedad y actualidad', hi: 'समाज और समसामयिक घटनाएँ', ar: 'المجتمع والأحداث الجارية' },
    xp: 50,
    objective: 'Use advanced societal vocabulary to discuss current issues in Canada and the world — essential for TEF speaking and writing tasks at CLB 7–9.',
    grammar: {
      title: 'Nominalisation & Passive Voice',
      explanation: 'At B2 level, TEF examiners expect formal register. Master two key tools: nominalisation (turning verbs into nouns) and the passive voice (être + past participle). These make your writing and speaking sound educated and precise.',
      points: [
        'Nominalisation: développer → le développement | décider → la décision | égal → l\'égalité | mondialiser → la mondialisation',
        'Passive voice: être + past participle (agrees in gender/number with subject)',
        'Active: Le gouvernement finance les hôpitaux. → Passive: Les hôpitaux sont financés par le gouvernement.',
        'Past passive: La loi a été adoptée. | Future passive: Le rapport sera publié.',
        'When to use passive: when the actor is unknown, unimportant, or for formal emphasis',
        'TEF tip: nominalisation in writing scores higher — use "la mise en œuvre" not "quand on met en œuvre"',
      ],
      examples: [
        'La croissance des inégalités sociales préoccupe les experts. (nominalisation of croître)',
        'Des mesures pour le logement abordable ont été annoncées hier. (passive past)',
        'L\'intelligence artificielle sera intégrée dans le marché du travail. (future passive)',
        'La protection des droits de l\'homme est garantie par la Constitution.',
        'La francophonie est célébrée chaque année dans plus de 80 pays.',
      ]
    },
    vocab: [
      { fr: 'le développement durable', en: 'sustainable development', example: 'Le Canada s\'est engagé en faveur du développement durable d\'ici 2050.' },
      { fr: 'les changements climatiques', en: 'climate change', example: 'Les changements climatiques obligent les gouvernements à revoir leurs politiques énergétiques.' },
      { fr: 'la mondialisation', en: 'globalization', example: 'La mondialisation a profondément transformé le marché du travail canadien.' },
      { fr: 'l\'inégalité sociale', en: 'social inequality', example: 'La pandémie a accentué les inégalités sociales entre les différentes couches de la population.' },
      { fr: 'le marché du travail', en: 'job market / labour market', example: 'L\'intelligence artificielle bouleverse le marché du travail dans de nombreux secteurs.' },
      { fr: 'l\'intelligence artificielle', en: 'artificial intelligence', example: 'L\'intelligence artificielle soulève des questions éthiques importantes sur la vie privée.' },
      { fr: 'la diversité culturelle', en: 'cultural diversity', example: 'La diversité culturelle est l\'une des richesses fondamentales du Canada.' },
      { fr: 'les droits de l\'homme', en: 'human rights', example: 'Le respect des droits de l\'homme est une condition essentielle à la démocratie.' },
      { fr: 'la santé publique', en: 'public health', example: 'La crise sanitaire a mis en évidence les faiblesses du système de santé publique.' },
      { fr: 'le logement abordable', en: 'affordable housing', example: 'La pénurie de logements abordables touche particulièrement les jeunes familles dans les grandes villes.' },
      { fr: 'la francophonie', en: 'the French-speaking world', example: 'Le Québec joue un rôle central dans la promotion de la francophonie en Amérique du Nord.' },
    ],
    dialogue: {
      title: 'Une discussion sur l\'actualité',
      context: 'Two colleagues — Amara and Philippe — discuss current issues in Canada during a lunch break.',
      lines: [
        { speaker: 'Amara', text: 'Tu as vu les nouvelles ce matin ? Le gouvernement vient d\'annoncer de nouvelles mesures pour le logement abordable.' },
        { speaker: 'Philippe', text: 'Oui, j\'ai lu ça. C\'est une bonne nouvelle, mais je me demande si ça suffira. La crise du logement est liée à des problèmes plus profonds — la mondialisation, la spéculation immobilière...' },
        { speaker: 'Amara', text: 'Exactement. Et il y a aussi la question de l\'inégalité sociale. Les gens qui ont le plus besoin d\'aide sont souvent ceux qui ont le moins accès aux ressources.' },
        { speaker: 'Philippe', text: 'Sans parler de l\'impact de l\'intelligence artificielle sur le marché du travail. Des milliers d\'emplois risquent de disparaître dans les prochaines années.' },
        { speaker: 'Amara', text: 'C\'est vrai, mais l\'IA crée aussi de nouveaux emplois. Le défi, c\'est la formation. Il faut investir dans l\'éducation et le développement durable en même temps.' },
        { speaker: 'Philippe', text: 'Tu as raison. Et n\'oublions pas les changements climatiques — tout est interconnecté. La santé publique, l\'économie, les droits de l\'homme... On ne peut pas traiter ces problèmes séparément.' },
        { speaker: 'Amara', text: 'C\'est justement ce que je dis à mes étudiants. La diversité culturelle du Canada est notre force — nous avons des perspectives différentes pour trouver des solutions communes.' },
        { speaker: 'Philippe', text: 'Bien dit. Et la francophonie nous connecte à tout un réseau mondial d\'idées et de solutions. On n\'est pas seuls face à ces défis.' },
      ],
      keyPhrases: [
        { fr: 'je me demande si', en: 'I wonder whether' },
        { fr: 'liée à des problèmes plus profonds', en: 'linked to deeper problems' },
        { fr: 'sans parler de', en: 'not to mention' },
        { fr: 'tout est interconnecté', en: 'everything is interconnected' },
        { fr: 'on ne peut pas traiter séparément', en: 'you can\'t address them separately' },
      ]
    },
    speaking: {
      prompt: 'You are asked to give your opinion on the following statement: "L\'intelligence artificielle représente une menace pour le marché du travail canadien plus qu\'une opportunité." Do you agree or disagree? Support your position with examples and nuance.',
      clbLevel: 'CLB 7–9',
      timeLimit: '2–3 minutes',
      tips: [
        'Open with a clear position: "Je suis en partie d\'accord avec cette affirmation, cependant..."',
        'Use at least 4 vocabulary words from this lesson naturally',
        'Structure: position → 2 arguments in favour → 1 counterargument → nuanced conclusion',
        'Use connectors: certes, cependant, en revanche, par conséquent, néanmoins',
        'Give a Canadian example: "Au Québec, le secteur manufacturier..." or "Selon Statistique Canada..."',
        'End with a nuanced view — examiners reward complexity over a simple yes/no',
        'Avoid filler sounds (euh, ben) — take a breath and pause instead',
      ],
      sampleOpener: 'L\'intelligence artificielle transforme indubitablement le marché du travail. Certes, certains emplois sont menacés, notamment dans les secteurs de la production et des services. Cependant, je crois que les opportunités surpassent les risques, à condition d\'investir dans la formation professionnelle et le développement durable de nos ressources humaines...',
    },
    writing: {
      prompt: 'Dans un texte de 200–250 mots, répondez à la question suivante : "La mondialisation contribue-t-elle à réduire ou à aggraver les inégalités sociales au Canada ?" Défendez votre point de vue avec des arguments précis.',
      clbLevel: 'CLB 7–9',
      wordCount: '200–250 mots',
      structure: [
        { part: 'Introduction (30–40 mots)', instruction: 'Introduce the debate, briefly define key terms (mondialisation, inégalité sociale), and announce your position clearly.' },
        { part: 'Thèse — Arguments (70–80 mots)', instruction: 'Present 2 arguments supporting one side. Use: "Tout d\'abord... De plus... En effet..." Include a specific example from Canadian or world context.' },
        { part: 'Antithèse — Nuance (60–70 mots)', instruction: 'Acknowledge the opposing view honestly. Use: "Cependant... Néanmoins... Il faut reconnaître que..." Show you understand the complexity.' },
        { part: 'Conclusion (30–40 mots)', instruction: 'Synthesise your position. Use: "En définitive... En somme... Il convient donc de..." Do not introduce new ideas — close with a forward-looking statement.' },
      ],
      usefulExpressions: [
        'D\'une part... d\'autre part... (on one hand... on the other...)',
        'Force est de constater que... (one must acknowledge that...)',
        'Cette tendance s\'explique par... (this trend is explained by...)',
        'Les données de Statistique Canada montrent que... (Statistics Canada data shows...)',
        'Il serait réducteur de prétendre que... (it would be simplistic to claim that...)',
      ],
    },
    exercises: [
      // MCQ (3)
      { type: 'mcq', question: 'A journalist writes: "Des milliers d\'emplois ont été supprimés par l\'IA." What tense is this passive construction?', options: ['Present passive', 'Past passive (passé composé)', 'Future passive', 'Conditional passive'], answer: 1 },
      { type: 'mcq', question: 'Which sentence uses nominalisation correctly in formal French?', options: ['"Il faut que les gens s\'égalisent davantage."', '"La réduction des inégalités sociales est urgente."', '"On doit rendre le logement plus abordable vite."', '"Les droits de l\'homme doivent être respectés par tout le monde partout."'], answer: 1 },
      { type: 'mcq', question: 'In a TEF speaking task about social issues, which opener best signals B2-level register?', options: ['"Je pense que c\'est un grand problème."', '"C\'est très important pour tout le monde."', '"Cette question soulève des enjeux fondamentaux pour la cohésion sociale."', '"Les gens ont beaucoup de difficultés avec ça."'], answer: 2 },
      // Fill in the blanks (3)
      { type: 'fill', sentence: 'Le Canada s\'est engagé en faveur du ___ durable pour lutter contre les changements ___.', blanks: ['développement', 'climatiques'], hint: 'sustainable ___ / climate ___' },
      { type: 'fill', sentence: 'La ___ culturelle du Canada est renforcée par la ___, qui connecte des millions de francophones dans le monde.', blanks: ['diversité', 'francophonie'], hint: 'cultural ___ / French-speaking world' },
      { type: 'fill', sentence: 'L\'___ artificielle transforme le ___ du travail, créant de nouvelles opportunités mais aussi de nouvelles inégalités.', blanks: ['intelligence', 'marché'], hint: 'artificial ___ / labour ___' },
    ]
  },

  'b2-3': {
    id: 'b2-3', moduleId: 'B2',
    title: { en: 'Writing Strategies — Structuring Arguments', pa: 'ਲਿਖਾਈ ਦੀਆਂ ਰਣਨੀਤੀਆਂ', es: 'Estrategias de escritura', hi: 'लेखन रणनीतियाँ', ar: 'استراتيجيات الكتابة' },
    xp: 40,
    vocab: [
      { fr: 'tout d\'abord', en: 'first of all', example: 'Tout d\'abord, il convient de définir le sujet.' },
      { fr: 'dans un premier temps', en: 'firstly', example: 'Dans un premier temps, nous analyserons les causes.' },
      { fr: 'ensuite / puis', en: 'then / next', example: 'Ensuite, nous examinerons les conséquences.' },
      { fr: 'de plus / par ailleurs', en: 'moreover', example: 'De plus, les études confirment cette tendance.' },
      { fr: 'enfin / pour terminer', en: 'finally', example: 'Enfin, il faut envisager des solutions.' },
      { fr: 'en conclusion', en: 'in conclusion', example: 'En conclusion, ce problème nécessite une action collective.' },
      { fr: 'il convient de', en: 'it is appropriate to', example: 'Il convient de nuancer cette affirmation.' },
      { fr: 'en définitive', en: 'ultimately', example: 'En définitive, c\'est l\'utilisateur qui décide.' },
      { fr: 'certes... mais', en: 'admittedly... but', example: 'Certes, la tâche est difficile, mais elle est réalisable.' },
      { fr: 'd\'autant plus que', en: 'all the more so because', example: 'C\'est important, d\'autant plus que les délais sont courts.' },
    ],
    grammar: {
      title: 'TEF Writing Structure: Thesis, Antithesis, Synthesis',
      explanation: 'TEF writing tasks require the classic French essay structure (thèse-antithèse-synthèse) that examiners expect.',
      points: [
        'Introduction: Present topic, announce your plan',
        'Thèse (Part 1): Arguments in favour of one position',
        'Antithèse (Part 2): Opposing arguments honestly presented',
        'Synthèse/Conclusion: Nuanced personal position',
        'Each paragraph: topic sentence + development + example + transition',
        'TEF writing: 150-250 words, formal register, varied connectors essential',
      ],
      examples: [
        'Intro: "La question de X est au cœur du débat. Dans un premier temps... puis..."',
        'Thesis: "Tout d\'abord, il convient de souligner que... En effet,... De plus,..."',
        'Antithesis: "Cependant, cette position mérite d\'être nuancée. Par ailleurs,..."',
        'Conclusion: "En définitive, bien que les arguments soient nombreux des deux côtés..."',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'What does "certes... mais" express?', options: ['addition', 'admitting a point then countering it', 'consequence', 'cause'], answer: 1 },
      { type: 'mcq', question: '"En définitive" means:', options: ['firstly', 'furthermore', 'ultimately', 'nevertheless'], answer: 2 },
      { type: 'mcq', question: 'What structure does formal French writing follow?', options: ['intro-body-conclusion', 'thèse-antithèse-synthèse', 'problem-solution', 'narrative arc'], answer: 1 },
      { type: 'mcq', question: '"D\'autant plus que" means:', options: ['despite the fact', 'all the more so because', 'as a result', 'on the other hand'], answer: 1 },
      { type: 'mcq', question: '"Il convient de" means:', options: ['it is impossible to', 'it is appropriate to', 'it is obvious that', 'it is forbidden to'], answer: 1 },
    ]
  },

  'b2-4': {
    id: 'b2-4', moduleId: 'B2',
    title: { en: 'Reading Strategies & Relative Pronouns', pa: 'ਪੜ੍ਹਾਈ ਦੀਆਂ ਰਣਨੀਤੀਆਂ', es: 'Estrategias de lectura', hi: 'पठन रणनीतियाँ', ar: 'استراتيجيات القراءة' },
    xp: 40,
    vocab: [
      { fr: 'l\'idée principale', en: 'main idea', example: 'Identifiez l\'idée principale de chaque paragraphe.' },
      { fr: 'implicite', en: 'implied', example: 'Le sens implicite n\'est pas dit directement.' },
      { fr: 'explicite', en: 'explicit', example: 'L\'information est explicite dans le premier paragraphe.' },
      { fr: 'le contexte', en: 'context', example: 'Utilisez le contexte pour deviner les mots inconnus.' },
      { fr: 'l\'auteur soutient que', en: 'the author argues that', example: 'L\'auteur soutient que l\'éducation doit être universelle.' },
      { fr: 'selon l\'auteur', en: 'according to the author', example: 'Selon l\'auteur, cette solution est insuffisante.' },
      { fr: 'déduire', en: 'to deduce', example: 'On peut déduire que l\'auteur est favorable à la réforme.' },
      { fr: 'paraphraser', en: 'to paraphrase', example: 'Paraphrasez cette phrase avec vos propres mots.' },
    ],
    grammar: {
      title: 'Relative Pronouns: qui, que, dont, où, lequel',
      explanation: 'Relative pronouns link clauses and are used extensively in formal French texts.',
      points: [
        'QUI = subject: L\'homme qui parle est mon patron.',
        'QUE = object: Le livre que je lis est intéressant.',
        'DONT = replaces de + noun: La ville dont je parle est Montréal.',
        'OÙ = place or time: La maison où j\'habite est grande.',
        'LEQUEL/LAQUELLE = after prepositions: La raison pour laquelle je pars.',
        'CE QUI / CE QUE / CE DONT = what/that which: Ce qui m\'intéresse, c\'est le français.',
      ],
      examples: [
        'L\'étudiant qui travaille le plus réussit.',
        'Le cours que tu suis est excellent.',
        'La ville dont il rêve est Paris.',
        'L\'année où j\'ai immigré était difficile.',
        'Ce dont j\'ai besoin, c\'est de pratiquer.',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Complete: "L\'homme ___ parle est directeur."', options: ['que', 'dont', 'qui', 'où'], answer: 2 },
      { type: 'mcq', question: 'Complete: "Le livre ___ je lis est fascinant."', options: ['qui', 'que', 'dont', 'lequel'], answer: 1 },
      { type: 'mcq', question: 'Complete: "La ville ___ il vient est Lyon."', options: ['que', 'qui', 'dont', 'où'], answer: 2 },
      { type: 'mcq', question: 'What does "implicite" mean?', options: ['explicit', 'implied', 'important', 'incorrect'], answer: 1 },
      { type: 'mcq', question: 'Complete: "La raison pour ___ je pars est personnelle."', options: ['qui', 'que', 'laquelle', 'dont'], answer: 2 },
      { type: 'mcq', question: '"Ce dont j\'ai besoin" means:', options: ['what I want', 'what I need', 'what I like', 'what I think'], answer: 1 },
    ]
  },

  'tef-1': {
    id: 'tef-1', moduleId: 'TEF',
    title: { en: 'TEF Reading — Strategy & Techniques', pa: 'TEF ਪੜ੍ਹਨ ਦੀਆਂ ਰਣਨੀਤੀਆਂ', es: 'Lectura TEF', hi: 'TEF पठन रणनीति', ar: 'استراتيجية القراءة في TEF' },
    xp: 50,
    vocab: [
      { fr: 'survoler le texte', en: 'to skim the text', example: 'Survolez le texte en 30 secondes avant de lire les questions.' },
      { fr: 'repérer les mots-clés', en: 'to identify keywords', example: 'Repérez les mots-clés dans chaque question.' },
      { fr: 'l\'idée directrice', en: 'the main idea', example: 'Quelle est l\'idée directrice de ce texte ?' },
      { fr: 'un piège', en: 'a trap', example: 'Méfiez-vous des pièges dans les réponses !' },
      { fr: 'reformuler', en: 'to rephrase', example: 'La bonne réponse est souvent une reformulation.' },
      { fr: 'la structure du texte', en: 'text structure', example: 'Analysez la structure avant de répondre.' },
    ],
    grammar: {
      title: 'TEF Reading: Official Format & Winning Strategies',
      explanation: 'The TEF reading section tests your ability to understand authentic French texts. Knowing the format is half the battle.',
      points: [
        'Format: 3 texts of increasing difficulty, 50 minutes, multiple choice',
        'Text types: articles, letters, advertisements, reports, literary extracts',
        'Skills tested: main idea, specific details, implicit meaning, vocabulary in context',
        'Strategy 1: Read all questions FIRST, then read the text',
        'Strategy 2: Answers are ALWAYS in the text — never guess from general knowledge',
        'Strategy 3: Correct answers paraphrase, they do not copy the text',
        'Strategy 4: Eliminate obviously wrong answers first',
        'Common traps: partially correct answers, words from text used in wrong context',
      ],
      examples: [
        'Main idea questions → Look at introduction and conclusion',
        'Specific detail → Scan for the relevant section only',
        'Vocabulary question → Use context clues and elimination',
        'Implicit meaning → Look for what author implies but does not state',
        'According to the text → Answer must be in text, not from your knowledge',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'In TEF reading, what should you read FIRST?', options: ['the text', 'the title', 'the questions', 'the footnotes'], answer: 2 },
      { type: 'mcq', question: 'Correct answers in TEF reading are usually:', options: ['copied from text', 'reformulations/paraphrases', 'from general knowledge', 'the longest option'], answer: 1 },
      { type: 'mcq', question: 'What does "survoler le texte" mean?', options: ['to read carefully', 'to skim the text', 'to translate', 'to summarize'], answer: 1 },
      { type: 'mcq', question: 'How long is the TEF reading section?', options: ['30 minutes', '40 minutes', '50 minutes', '60 minutes'], answer: 2 },
      { type: 'mcq', question: 'What is a "piège" in TEF context?', options: ['a text type', 'a trap/trick', 'a grammar rule', 'a text structure'], answer: 1 },
    ]
  },

  'tef-2': {
    id: 'tef-2', moduleId: 'TEF',
    title: { en: 'TEF Writing — Letter & Essay Mastery', pa: 'TEF ਲਿਖਾਈ', es: 'Escritura TEF', hi: 'TEF लेखन', ar: 'الكتابة في TEF' },
    xp: 50,
    vocab: [
      { fr: 'Madame, Monsieur,', en: 'Dear Sir/Madam (formal opening)', example: 'Madame, Monsieur, je me permets de vous écrire...' },
      { fr: 'Je me permets de vous contacter', en: 'I am taking the liberty of contacting you', example: 'Je me permets de vous contacter au sujet de...' },
      { fr: 'Suite à', en: 'Following / Further to', example: 'Suite à notre entretien téléphonique...' },
      { fr: 'Je vous serais reconnaissant(e) de', en: 'I would be grateful if you could', example: 'Je vous serais reconnaissant de bien vouloir me répondre.' },
      { fr: 'Dans l\'attente de votre réponse', en: 'Awaiting your reply', example: 'Dans l\'attente de votre réponse, veuillez agréer...' },
      { fr: 'Veuillez agréer mes salutations distinguées', en: 'Yours faithfully (formal closing)', example: 'Veuillez agréer, Madame, mes salutations distinguées.' },
      { fr: 'Je tiens à souligner', en: 'I wish to emphasize', example: 'Je tiens à souligner l\'importance de ce projet.' },
    ],
    grammar: {
      title: 'TEF Writing Task Types & Scoring Breakdown',
      explanation: 'The TEF writing section has two tasks. Understanding what examiners look for dramatically improves your score.',
      points: [
        'Task 1 (100 words): Formal letter or email — formal register required',
        'Task 2 (200 words): Essay or opinion piece — structured argument required',
        'Scoring: Task completion, coherence/cohesion, vocabulary range, grammatical accuracy',
        'Formal letter structure: heading → opening → body → request → formal closing',
        'Essay structure: introduction (plan) → part 1 → part 2 → conclusion',
        'Use VARIETY of connectors, tenses, vocabulary — repetition loses points',
        'Avoid: anglicisms, informal language, unsupported claims',
        'Time: 20 min for Task 1, 35 min for Task 2, 5 min to review',
      ],
      examples: [
        'Formal opening: "Madame, Monsieur, Je me permets de vous écrire afin de..."',
        'Formal closing: "Dans l\'attente de votre réponse, veuillez agréer, Madame, l\'expression de mes salutations distinguées."',
        'Essay intro: "La question de [topic] est aujourd\'hui au cœur des préoccupations..."',
        'Essay conclusion: "En définitive, si [point 1] est indéniable, il convient néanmoins de nuancer..."',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How many words for TEF Writing Task 2?', options: ['100 words', '150 words', '200 words', '250 words'], answer: 2 },
      { type: 'mcq', question: 'Formal French letter closing:', options: ['Cordialement', 'Bisous', 'Veuillez agréer mes salutations distinguées', 'À bientôt'], answer: 2 },
      { type: 'mcq', question: '"Suite à" means:', options: ['Regarding', 'Following/Further to', 'Despite', 'Because of'], answer: 1 },
      { type: 'mcq', question: 'In TEF writing, what to AVOID:', options: ['long sentences', 'connectors', 'informal language', 'examples'], answer: 2 },
      { type: 'mcq', question: 'Time for TEF Writing Task 1:', options: ['10 minutes', '15 minutes', '20 minutes', '30 minutes'], answer: 2 },
    ]
  },

  'tef-3': {
    id: 'tef-3', moduleId: 'TEF',
    title: { en: 'TEF Listening — Deep Practice', pa: 'TEF ਸੁਣਾਈ ਅਭਿਆਸ', es: 'Comprensión auditiva TEF', hi: 'TEF श्रवण अभ्यास', ar: 'الاستماع في TEF' },
    xp: 50,
    vocab: [
      { fr: 'l\'intonation', en: 'intonation', example: 'L\'intonation indique si c\'est une question.' },
      { fr: 'le débit', en: 'speech rate', example: 'Le débit des locuteurs natifs est rapide.' },
      { fr: 'la liaison', en: 'linking sounds', example: 'Les liaisons changent la prononciation.' },
      { fr: 'distinguer', en: 'to distinguish', example: 'Distinguez les sons similaires comme u/ou.' },
      { fr: 'prendre des notes', en: 'to take notes', example: 'Prenez des notes en écoutant.' },
      { fr: 'l\'accent québécois', en: 'Quebec accent', example: 'L\'accent québécois est différent du français de France.' },
    ],
    grammar: {
      title: 'TEF Listening Format & Proven Strategies',
      explanation: 'The TEF listening section tests comprehension of authentic spoken French across three parts.',
      points: [
        'Format: 3 parts, 13 questions, 40 minutes, audio plays ONCE in real exam',
        'Part 1: 6 short dialogues (daily situations) — CLB 5-7',
        'Part 2: 4 medium documents (radio, announcements) — CLB 7-9',
        'Part 3: 3 long interviews/debates — CLB 9-12',
        'Strategy 1: Read ALL answer options before audio plays',
        'Strategy 2: Focus on WHO, WHAT, WHY, WHERE, WHEN, HOW',
        'Strategy 3: Write down numbers, names, times immediately',
        'Strategy 4: Eliminate obvious wrong answers',
        'Quebec French: "tu as" sounds like "t\'as", "je suis" informally sounds like "chu"',
      ],
      examples: [
        'Dialogues: Listen for the REASON for the action (pourquoi)',
        'Announcements: Listen for WHAT and WHEN first',
        'Interviews: Listen for the speaker\'s OPINION/POSITION',
        'Trap: A word from recording appearing in a wrong answer',
        'Practice: Watch RDI and listen to Radio-Canada podcasts',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'How many times does audio play in real TEF?', options: ['once', 'twice', 'three times', 'as needed'], answer: 0 },
      { type: 'mcq', question: 'What to do BEFORE audio plays?', options: ['close eyes', 'read all answer options', 'write vocabulary', 'look at clock'], answer: 1 },
      { type: 'mcq', question: 'What is "la liaison"?', options: ['formal language', 'linking sounds between words', 'an accent mark', 'a verb type'], answer: 1 },
      { type: 'mcq', question: 'How many questions in TEF listening?', options: ['10', '13', '15', '20'], answer: 1 },
      { type: 'mcq', question: 'What does "le débit" mean in speech context?', options: ['accent', 'vocabulary', 'speech rate', 'grammar'], answer: 2 },
    ]
  },

  'tef-4': {
    id: 'tef-4', moduleId: 'TEF',
    title: { en: 'TEF Speaking — Scoring CLB 7+', pa: 'TEF ਬੋਲਣ — CLB 7+', es: 'Expresión oral TEF', hi: 'TEF बोलना', ar: 'التعبير الشفهي في TEF' },
    xp: 50,
    vocab: [
      { fr: 'développer ses idées', en: 'to develop one\'s ideas', example: 'Développez vos idées avec des exemples concrets.' },
      { fr: 'justifier son point de vue', en: 'to justify one\'s point of view', example: 'Justifiez votre point de vue avec des arguments.' },
      { fr: 'enchaîner les idées', en: 'to link ideas', example: 'Enchaînez vos idées avec des connecteurs.' },
      { fr: 'reformuler', en: 'to rephrase', example: 'Si vous faites une erreur, reformulez.' },
      { fr: 'gagner du temps', en: 'to buy time', example: 'Utilisez des expressions pour gagner du temps.' },
      { fr: 'C\'est-à-dire que', en: 'That is to say', example: 'C\'est-à-dire que la situation est complexe.' },
      { fr: 'En fait', en: 'In fact / Actually', example: 'En fait, je pense que c\'est plus compliqué.' },
      { fr: 'Permettez-moi de réfléchir', en: 'Allow me to think', example: 'Permettez-moi de réfléchir un instant...' },
    ],
    grammar: {
      title: 'TEF Speaking: Tasks, Scoring & Winning Strategies',
      explanation: 'The TEF speaking section evaluates your ability to communicate naturally across three tasks.',
      points: [
        'Task 1 — Monologue: Describe/narrate for 2-3 min (1 min prep)',
        'Task 2 — Interaction: Dialogue simulation 3-4 min',
        'Task 3 — Point of view: Defend a position 4-5 min (1.5 min prep)',
        'Scoring: Fluency (25%) | Vocabulary (25%) | Grammar (25%) | Coherence (25%)',
        'CLB 7: Speak with some fluency, use varied vocabulary, minimal blocking',
        'Fluency tip: Use fillers — "Euh... / C\'est-à-dire que... / En fait... / Voyons voir..."',
        'Vocabulary tip: Use synonyms, avoid repeating the same word',
        'Grammar tip: Mix tenses — present, past, future, conditional',
        'NEVER silent for more than 3 seconds — say something even imperfectly',
      ],
      examples: [
        'Time-buyers: "C\'est une excellente question... / Permettez-moi de réfléchir..."',
        'Linking: "D\'une part... d\'autre part... / Non seulement... mais aussi..."',
        'Self-correction: "Je voulais dire... / Ce que je veux dire, c\'est que..."',
        'Monologue start: "Je vais vous parler de... Dans un premier temps..."',
        'Giving opinion: "Pour ma part, je pense que... / À mon sens..."',
      ]
    },
    exercises: [
      { type: 'mcq', question: 'Vocabulary is what % of TEF speaking score?', options: ['10%', '20%', '25%', '30%'], answer: 2 },
      { type: 'mcq', question: 'How long is TEF Speaking Task 1?', options: ['1-2 min', '2-3 min', '3-4 min', '5 min'], answer: 1 },
      { type: 'mcq', question: 'What to do if you make a speaking mistake?', options: ['stop', 'stay silent', 'self-correct and continue', 'start over'], answer: 2 },
      { type: 'mcq', question: 'What is a "filler expression" used for?', options: ['add vocabulary', 'buy time/avoid silence', 'end a sentence', 'ask a question'], answer: 1 },
      { type: 'mcq', question: 'CLB 7 speaking requires:', options: ['perfect grammar', 'native fluency', 'some fluency + varied vocabulary', 'no errors'], answer: 2 },
      { type: 'mcq', question: 'How many tasks in TEF speaking?', options: ['1', '2', '3', '4'], answer: 2 },
    ]
  },
}